from .async_client import LocalServicesLeadServiceAsyncClient as LocalServicesLeadServiceAsyncClient
from .client import LocalServicesLeadServiceClient as LocalServicesLeadServiceClient

__all__ = ['LocalServicesLeadServiceClient', 'LocalServicesLeadServiceAsyncClient']
