import grpc
from .base import ProductLinkInvitationServiceTransport
from google.ads.googleads.v20.services.types import product_link_invitation_service
from google.api_core import gapic_v1
from google.auth import credentials as ga_credentials
from typing import Callable, Sequence, Tuple

__all__ = ['ProductLinkInvitationServiceGrpcTransport']

class _LoggingClientInterceptor(grpc.UnaryUnaryClientInterceptor):
    def intercept_unary_unary(self, continuation, client_call_details, request): ...

class ProductLinkInvitationServiceGrpcTransport(ProductLinkInvitationServiceTransport):
    def __init__(self, *, host: str = 'googleads.googleapis.com', credentials: ga_credentials.Credentials | None = None, credentials_file: str | None = None, scopes: Sequence[str] | None = None, channel: grpc.Channel | Callable[..., grpc.Channel] | None = None, api_mtls_endpoint: str | None = None, client_cert_source: Callable[[], Tuple[bytes, bytes]] | None = None, ssl_channel_credentials: grpc.ChannelCredentials | None = None, client_cert_source_for_mtls: Callable[[], Tuple[bytes, bytes]] | None = None, quota_project_id: str | None = None, client_info: gapic_v1.client_info.ClientInfo = ..., always_use_jwt_access: bool | None = False, api_audience: str | None = None) -> None: ...
    @classmethod
    def create_channel(cls, host: str = 'googleads.googleapis.com', credentials: ga_credentials.Credentials | None = None, credentials_file: str | None = None, scopes: Sequence[str] | None = None, quota_project_id: str | None = None, **kwargs) -> grpc.Channel: ...
    @property
    def grpc_channel(self) -> grpc.Channel: ...
    @property
    def create_product_link_invitation(self) -> Callable[[product_link_invitation_service.CreateProductLinkInvitationRequest], product_link_invitation_service.CreateProductLinkInvitationResponse]: ...
    @property
    def update_product_link_invitation(self) -> Callable[[product_link_invitation_service.UpdateProductLinkInvitationRequest], product_link_invitation_service.UpdateProductLinkInvitationResponse]: ...
    @property
    def remove_product_link_invitation(self) -> Callable[[product_link_invitation_service.RemoveProductLinkInvitationRequest], product_link_invitation_service.RemoveProductLinkInvitationResponse]: ...
    def close(self) -> None: ...
    @property
    def kind(self) -> str: ...
