import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class LeadFormFieldUserInputTypeEnum(proto.Message):
    class LeadFormFieldUserInputType(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        FULL_NAME: int
        EMAIL: int
        PHONE_NUMBER: int
        POSTAL_CODE: int
        STREET_ADDRESS: int
        CITY: int
        REGION: int
        COUNTRY: int
        WORK_EMAIL: int
        COMPANY_NAME: int
        WORK_PHONE: int
        JOB_TITLE: int
        GOVERNMENT_ISSUED_ID_CPF_BR: int
        GOVERNMENT_ISSUED_ID_DNI_AR: int
        GOVERNMENT_ISSUED_ID_DNI_PE: int
        GOVERNMENT_ISSUED_ID_RUT_CL: int
        GOVERNMENT_ISSUED_ID_CC_CO: int
        GOVERNMENT_ISSUED_ID_CI_EC: int
        GOVERNMENT_ISSUED_ID_RFC_MX: int
        FIRST_NAME: int
        LAST_NAME: int
        VEHICLE_MODEL: int
        VEHICLE_TYPE: int
        PREFERRED_DEALERSHIP: int
        VEHICLE_PURCHASE_TIMELINE: int
        VEHICLE_OWNERSHIP: int
        VEHICLE_PAYMENT_TYPE: int
        VEHICLE_CONDITION: int
        COMPANY_SIZE: int
        ANNUAL_SALES: int
        YEARS_IN_BUSINESS: int
        JOB_DEPARTMENT: int
        JOB_ROLE: int
        OVER_18_AGE: int
        OVER_19_AGE: int
        OVER_20_AGE: int
        OVER_21_AGE: int
        OVER_22_AGE: int
        OVER_23_AGE: int
        OVER_24_AGE: int
        OVER_25_AGE: int
        OVER_26_AGE: int
        OVER_27_AGE: int
        OVER_28_AGE: int
        OVER_29_AGE: int
        OVER_30_AGE: int
        OVER_31_AGE: int
        OVER_32_AGE: int
        OVER_33_AGE: int
        OVER_34_AGE: int
        OVER_35_AGE: int
        OVER_36_AGE: int
        OVER_37_AGE: int
        OVER_38_AGE: int
        OVER_39_AGE: int
        OVER_40_AGE: int
        OVER_41_AGE: int
        OVER_42_AGE: int
        OVER_43_AGE: int
        OVER_44_AGE: int
        OVER_45_AGE: int
        OVER_46_AGE: int
        OVER_47_AGE: int
        OVER_48_AGE: int
        OVER_49_AGE: int
        OVER_50_AGE: int
        OVER_51_AGE: int
        OVER_52_AGE: int
        OVER_53_AGE: int
        OVER_54_AGE: int
        OVER_55_AGE: int
        OVER_56_AGE: int
        OVER_57_AGE: int
        OVER_58_AGE: int
        OVER_59_AGE: int
        OVER_60_AGE: int
        OVER_61_AGE: int
        OVER_62_AGE: int
        OVER_63_AGE: int
        OVER_64_AGE: int
        OVER_65_AGE: int
        EDUCATION_PROGRAM: int
        EDUCATION_COURSE: int
        PRODUCT: int
        SERVICE: int
        OFFER: int
        CATEGORY: int
        PREFERRED_CONTACT_METHOD: int
        PREFERRED_LOCATION: int
        PREFERRED_CONTACT_TIME: int
        PURCHASE_TIMELINE: int
        YEARS_OF_EXPERIENCE: int
        JOB_INDUSTRY: int
        LEVEL_OF_EDUCATION: int
        PROPERTY_TYPE: int
        REALTOR_HELP_GOAL: int
        PROPERTY_COMMUNITY: int
        PRICE_RANGE: int
        NUMBER_OF_BEDROOMS: int
        FURNISHED_PROPERTY: int
        PETS_ALLOWED_PROPERTY: int
        NEXT_PLANNED_PURCHASE: int
        EVENT_SIGNUP_INTEREST: int
        PREFERRED_SHOPPING_PLACES: int
        FAVORITE_BRAND: int
        TRANSPORTATION_COMMERCIAL_LICENSE_TYPE: int
        EVENT_BOOKING_INTEREST: int
        DESTINATION_COUNTRY: int
        DESTINATION_CITY: int
        DEPARTURE_COUNTRY: int
        DEPARTURE_CITY: int
        DEPARTURE_DATE: int
        RETURN_DATE: int
        NUMBER_OF_TRAVELERS: int
        TRAVEL_BUDGET: int
        TRAVEL_ACCOMMODATION: int
