import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class ServedAssetFieldTypeEnum(proto.Message):
    class ServedAssetFieldType(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        HEADLINE_1: int
        HEADLINE_2: int
        HEADLINE_3: int
        DESCRIPTION_1: int
        DESCRIPTION_2: int
        HEADLINE: int
        HEADLINE_IN_PORTRAIT: int
        LONG_HEADLINE: int
        DESCRIPTION: int
        DESCRIPTION_IN_PORTRAIT: int
        BUSINESS_NAME_IN_PORTRAIT: int
        BUSINESS_NAME: int
        MARKETING_IMAGE: int
        MARKETING_IMAGE_IN_PORTRAIT: int
        SQUARE_MARKETING_IMAGE: int
        PORTRAIT_MARKETING_IMAGE: int
        LOGO: int
        LANDSCAPE_LOGO: int
        CALL_TO_ACTION: int
        YOU_TUBE_VIDEO: int
        SITELINK: int
        CALL: int
        MOBILE_APP: int
        CALLOUT: int
        STRUCTURED_SNIPPET: int
        PRICE: int
        PROMOTION: int
        AD_IMAGE: int
        LEAD_FORM: int
        BUSINESS_LOGO: int
