import grpc
from .base import DataLinkServiceTransport
from google.ads.googleads.v19.services.types import data_link_service
from google.api_core import gapic_v1
from google.auth import credentials as ga_credentials
from grpc.experimental import aio
from typing import Awaitable, Callable, Sequence, Tuple

__all__ = ['DataLinkServiceGrpcAsyncIOTransport']

class _LoggingClientAIOInterceptor(grpc.aio.UnaryUnaryClientInterceptor):
    async def intercept_unary_unary(self, continuation, client_call_details, request): ...

class DataLinkServiceGrpcAsyncIOTransport(DataLinkServiceTransport):
    @classmethod
    def create_channel(cls, host: str = 'googleads.googleapis.com', credentials: ga_credentials.Credentials | None = None, credentials_file: str | None = None, scopes: Sequence[str] | None = None, quota_project_id: str | None = None, **kwargs) -> aio.Channel: ...
    def __init__(self, *, host: str = 'googleads.googleapis.com', credentials: ga_credentials.Credentials | None = None, credentials_file: str | None = None, scopes: Sequence[str] | None = None, channel: aio.Channel | Callable[..., aio.Channel] | None = None, api_mtls_endpoint: str | None = None, client_cert_source: Callable[[], Tuple[bytes, bytes]] | None = None, ssl_channel_credentials: grpc.ChannelCredentials | None = None, client_cert_source_for_mtls: Callable[[], Tuple[bytes, bytes]] | None = None, quota_project_id: str | None = None, client_info: gapic_v1.client_info.ClientInfo = ..., always_use_jwt_access: bool | None = False, api_audience: str | None = None) -> None: ...
    @property
    def grpc_channel(self) -> aio.Channel: ...
    @property
    def create_data_link(self) -> Callable[[data_link_service.CreateDataLinkRequest], Awaitable[data_link_service.CreateDataLinkResponse]]: ...
    @property
    def remove_data_link(self) -> Callable[[data_link_service.RemoveDataLinkRequest], Awaitable[data_link_service.RemoveDataLinkResponse]]: ...
    @property
    def update_data_link(self) -> Callable[[data_link_service.UpdateDataLinkRequest], Awaitable[data_link_service.UpdateDataLinkResponse]]: ...
    def close(self): ...
    @property
    def kind(self) -> str: ...
