# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class AppCampaignBiddingStrategyGoalTypeEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    AppCampaignBiddingStrategyGoalTypeValue = typing___NewType(
        "AppCampaignBiddingStrategyGoalTypeValue", builtin___int
    )
    type___AppCampaignBiddingStrategyGoalTypeValue = (
        AppCampaignBiddingStrategyGoalTypeValue
    )
    AppCampaignBiddingStrategyGoalType: _AppCampaignBiddingStrategyGoalType
    class _AppCampaignBiddingStrategyGoalType(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(
            AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
            0,
        )
        UNKNOWN = typing___cast(
            AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
            1,
        )
        OPTIMIZE_INSTALLS_TARGET_INSTALL_COST = typing___cast(
            AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
            2,
        )
        OPTIMIZE_IN_APP_CONVERSIONS_TARGET_INSTALL_COST = typing___cast(
            AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
            3,
        )
        OPTIMIZE_IN_APP_CONVERSIONS_TARGET_CONVERSION_COST = typing___cast(
            AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
            4,
        )
        OPTIMIZE_RETURN_ON_ADVERTISING_SPEND = typing___cast(
            AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
            5,
        )
    UNSPECIFIED = typing___cast(
        AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
        0,
    )
    UNKNOWN = typing___cast(
        AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
        1,
    )
    OPTIMIZE_INSTALLS_TARGET_INSTALL_COST = typing___cast(
        AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
        2,
    )
    OPTIMIZE_IN_APP_CONVERSIONS_TARGET_INSTALL_COST = typing___cast(
        AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
        3,
    )
    OPTIMIZE_IN_APP_CONVERSIONS_TARGET_CONVERSION_COST = typing___cast(
        AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
        4,
    )
    OPTIMIZE_RETURN_ON_ADVERTISING_SPEND = typing___cast(
        AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalTypeValue,
        5,
    )
    type___AppCampaignBiddingStrategyGoalType = AppCampaignBiddingStrategyGoalType
    def __init__(self,) -> None: ...

type___AppCampaignBiddingStrategyGoalTypeEnum = AppCampaignBiddingStrategyGoalTypeEnum
