# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class FeedItemStatusEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    FeedItemStatusValue = typing___NewType("FeedItemStatusValue", builtin___int)
    type___FeedItemStatusValue = FeedItemStatusValue
    FeedItemStatus: _FeedItemStatus
    class _FeedItemStatus(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            FeedItemStatusEnum.FeedItemStatusValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 0)
        UNKNOWN = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 1)
        ENABLED = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 2)
        REMOVED = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 3)
    UNSPECIFIED = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 0)
    UNKNOWN = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 1)
    ENABLED = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 2)
    REMOVED = typing___cast(FeedItemStatusEnum.FeedItemStatusValue, 3)
    type___FeedItemStatus = FeedItemStatus
    def __init__(self,) -> None: ...

type___FeedItemStatusEnum = FeedItemStatusEnum
