# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class PolicyTopicEvidenceDestinationNotWorkingDeviceEnum(
    google___protobuf___message___Message
):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    PolicyTopicEvidenceDestinationNotWorkingDeviceValue = typing___NewType(
        "PolicyTopicEvidenceDestinationNotWorkingDeviceValue", builtin___int
    )
    type___PolicyTopicEvidenceDestinationNotWorkingDeviceValue = (
        PolicyTopicEvidenceDestinationNotWorkingDeviceValue
    )
    PolicyTopicEvidenceDestinationNotWorkingDevice: _PolicyTopicEvidenceDestinationNotWorkingDevice
    class _PolicyTopicEvidenceDestinationNotWorkingDevice(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(
            PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
            0,
        )
        UNKNOWN = typing___cast(
            PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
            1,
        )
        DESKTOP = typing___cast(
            PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
            2,
        )
        ANDROID = typing___cast(
            PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
            3,
        )
        IOS = typing___cast(
            PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
            4,
        )
    UNSPECIFIED = typing___cast(
        PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
        0,
    )
    UNKNOWN = typing___cast(
        PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
        1,
    )
    DESKTOP = typing___cast(
        PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
        2,
    )
    ANDROID = typing___cast(
        PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
        3,
    )
    IOS = typing___cast(
        PolicyTopicEvidenceDestinationNotWorkingDeviceEnum.PolicyTopicEvidenceDestinationNotWorkingDeviceValue,
        4,
    )
    type___PolicyTopicEvidenceDestinationNotWorkingDevice = (
        PolicyTopicEvidenceDestinationNotWorkingDevice
    )
    def __init__(self,) -> None: ...

type___PolicyTopicEvidenceDestinationNotWorkingDeviceEnum = (
    PolicyTopicEvidenceDestinationNotWorkingDeviceEnum
)
