"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ProductConditionEnum(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _ProductCondition(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProductCondition.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED = ProductConditionEnum.ProductCondition.V(0)
        UNKNOWN = ProductConditionEnum.ProductCondition.V(1)
        NEW = ProductConditionEnum.ProductCondition.V(3)
        REFURBISHED = ProductConditionEnum.ProductCondition.V(4)
        USED = ProductConditionEnum.ProductCondition.V(5)
    class ProductCondition(metaclass=_ProductCondition):
        V = typing.NewType("V", builtins.int)
    UNSPECIFIED = ProductConditionEnum.ProductCondition.V(0)
    UNKNOWN = ProductConditionEnum.ProductCondition.V(1)
    NEW = ProductConditionEnum.ProductCondition.V(3)
    REFURBISHED = ProductConditionEnum.ProductCondition.V(4)
    USED = ProductConditionEnum.ProductCondition.V(5)
    def __init__(
        self,
    ) -> None: ...

global___ProductConditionEnum = ProductConditionEnum
