# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class QuotaErrorEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    QuotaErrorValue = typing___NewType("QuotaErrorValue", builtin___int)
    type___QuotaErrorValue = QuotaErrorValue
    QuotaError: _QuotaError
    class _QuotaError(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            QuotaErrorEnum.QuotaErrorValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(QuotaErrorEnum.QuotaErrorValue, 0)
        UNKNOWN = typing___cast(QuotaErrorEnum.QuotaErrorValue, 1)
        RESOURCE_EXHAUSTED = typing___cast(QuotaErrorEnum.QuotaErrorValue, 2)
        ACCESS_PROHIBITED = typing___cast(QuotaErrorEnum.QuotaErrorValue, 3)
        RESOURCE_TEMPORARILY_EXHAUSTED = typing___cast(
            QuotaErrorEnum.QuotaErrorValue, 4
        )
    UNSPECIFIED = typing___cast(QuotaErrorEnum.QuotaErrorValue, 0)
    UNKNOWN = typing___cast(QuotaErrorEnum.QuotaErrorValue, 1)
    RESOURCE_EXHAUSTED = typing___cast(QuotaErrorEnum.QuotaErrorValue, 2)
    ACCESS_PROHIBITED = typing___cast(QuotaErrorEnum.QuotaErrorValue, 3)
    RESOURCE_TEMPORARILY_EXHAUSTED = typing___cast(QuotaErrorEnum.QuotaErrorValue, 4)
    type___QuotaError = QuotaError
    def __init__(self,) -> None: ...

type___QuotaErrorEnum = QuotaErrorEnum
