"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SizeLimitErrorEnum(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _SizeLimitError(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SizeLimitError.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED = SizeLimitErrorEnum.SizeLimitError.V(0)
        UNKNOWN = SizeLimitErrorEnum.SizeLimitError.V(1)
        REQUEST_SIZE_LIMIT_EXCEEDED = SizeLimitErrorEnum.SizeLimitError.V(2)
        RESPONSE_SIZE_LIMIT_EXCEEDED = SizeLimitErrorEnum.SizeLimitError.V(3)
    class SizeLimitError(metaclass=_SizeLimitError):
        V = typing.NewType("V", builtins.int)
    UNSPECIFIED = SizeLimitErrorEnum.SizeLimitError.V(0)
    UNKNOWN = SizeLimitErrorEnum.SizeLimitError.V(1)
    REQUEST_SIZE_LIMIT_EXCEEDED = SizeLimitErrorEnum.SizeLimitError.V(2)
    RESPONSE_SIZE_LIMIT_EXCEEDED = SizeLimitErrorEnum.SizeLimitError.V(3)
    def __init__(
        self,
    ) -> None: ...

global___SizeLimitErrorEnum = SizeLimitErrorEnum
