import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class AssetLinkErrorEnum(proto.Message):
    class AssetLinkError(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        PINNING_UNSUPPORTED: int
        UNSUPPORTED_FIELD_TYPE: int
        FIELD_TYPE_INCOMPATIBLE_WITH_ASSET_TYPE: int
        FIELD_TYPE_INCOMPATIBLE_WITH_CAMPAIGN_TYPE: int
        INCOMPATIBLE_ADVERTISING_CHANNEL_TYPE: int
        IMAGE_NOT_WITHIN_SPECIFIED_DIMENSION_RANGE: int
        INVALID_PINNED_FIELD: int
        MEDIA_BUNDLE_ASSET_FILE_SIZE_TOO_LARGE: int
        NOT_ENOUGH_AVAILABLE_ASSET_LINKS_FOR_VALID_COMBINATION: int
        NOT_ENOUGH_AVAILABLE_ASSET_LINKS_WITH_FALLBACK: int
        NOT_ENOUGH_AVAILABLE_ASSET_LINKS_WITH_FALLBACK_FOR_VALID_COMBINATION: int
        YOUTUBE_VIDEO_REMOVED: int
        YOUTUBE_VIDEO_TOO_LONG: int
        YOUTUBE_VIDEO_TOO_SHORT: int
        EXCLUDED_PARENT_FIELD_TYPE: int
        INVALID_STATUS: int
        YOUTUBE_VIDEO_DURATION_NOT_DEFINED: int
        CANNOT_CREATE_AUTOMATICALLY_CREATED_LINKS: int
        CANNOT_LINK_TO_AUTOMATICALLY_CREATED_ASSET: int
        CANNOT_MODIFY_ASSET_LINK_SOURCE: int
        CANNOT_LINK_LOCATION_LEAD_FORM_WITHOUT_LOCATION_ASSET: int
        CUSTOMER_NOT_VERIFIED: int
        UNSUPPORTED_CALL_TO_ACTION: int
        BRAND_ASSETS_NOT_LINKED_AT_ASSET_GROUP_LEVEL: int
        BRAND_ASSETS_NOT_LINKED_AT_CAMPAIGN_LEVEL: int
