# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class DeviceEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Device(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> DeviceEnum.Device: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[DeviceEnum.Device]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, DeviceEnum.Device]]: ...
        UNSPECIFIED = typing___cast(DeviceEnum.Device, 0)
        UNKNOWN = typing___cast(DeviceEnum.Device, 1)
        MOBILE = typing___cast(DeviceEnum.Device, 2)
        TABLET = typing___cast(DeviceEnum.Device, 3)
        DESKTOP = typing___cast(DeviceEnum.Device, 4)
        CONNECTED_TV = typing___cast(DeviceEnum.Device, 6)
        OTHER = typing___cast(DeviceEnum.Device, 5)
    UNSPECIFIED = typing___cast(DeviceEnum.Device, 0)
    UNKNOWN = typing___cast(DeviceEnum.Device, 1)
    MOBILE = typing___cast(DeviceEnum.Device, 2)
    TABLET = typing___cast(DeviceEnum.Device, 3)
    DESKTOP = typing___cast(DeviceEnum.Device, 4)
    CONNECTED_TV = typing___cast(DeviceEnum.Device, 6)
    OTHER = typing___cast(DeviceEnum.Device, 5)


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> DeviceEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
