# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class FeedItemTargetTypeEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    FeedItemTargetTypeValue = typing___NewType("FeedItemTargetTypeValue", builtin___int)
    type___FeedItemTargetTypeValue = FeedItemTargetTypeValue
    FeedItemTargetType: _FeedItemTargetType
    class _FeedItemTargetType(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            FeedItemTargetTypeEnum.FeedItemTargetTypeValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 0)
        UNKNOWN = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 1)
        CAMPAIGN = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 2)
        AD_GROUP = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 3)
        CRITERION = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 4)
    UNSPECIFIED = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 0)
    UNKNOWN = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 1)
    CAMPAIGN = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 2)
    AD_GROUP = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 3)
    CRITERION = typing___cast(FeedItemTargetTypeEnum.FeedItemTargetTypeValue, 4)
    type___FeedItemTargetType = FeedItemTargetType
    def __init__(self,) -> None: ...

type___FeedItemTargetTypeEnum = FeedItemTargetTypeEnum
