import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class AssetGroupListingGroupFilterErrorEnum(proto.Message):
    class AssetGroupListingGroupFilterError(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        TREE_TOO_DEEP: int
        UNIT_CANNOT_HAVE_CHILDREN: int
        SUBDIVISION_MUST_HAVE_EVERYTHING_ELSE_CHILD: int
        DIFFERENT_DIMENSION_TYPE_BETWEEN_SIBLINGS: int
        SAME_DIMENSION_VALUE_BETWEEN_SIBLINGS: int
        SAME_DIMENSION_TYPE_BETWEEN_ANCESTORS: int
        MULTIPLE_ROOTS: int
        INVALID_DIMENSION_VALUE: int
        MUST_REFINE_HIERARCHICAL_PARENT_TYPE: int
        INVALID_PRODUCT_BIDDING_CATEGORY: int
        CHANGING_CASE_VALUE_WITH_CHILDREN: int
        SUBDIVISION_HAS_CHILDREN: int
        CANNOT_REFINE_HIERARCHICAL_EVERYTHING_ELSE: int
        DIMENSION_TYPE_NOT_ALLOWED: int
        DUPLICATE_WEBPAGE_FILTER_UNDER_ASSET_GROUP: int
        LISTING_SOURCE_NOT_ALLOWED: int
        FILTER_EXCLUSION_NOT_ALLOWED: int
        MULTIPLE_LISTING_SOURCES: int
        MULTIPLE_WEBPAGE_CONDITION_TYPES_NOT_ALLOWED: int
        MULTIPLE_WEBPAGE_TYPES_PER_ASSET_GROUP: int
        PAGE_FEED_FILTER_HAS_PARENT: int
        MULTIPLE_OPERATIONS_ON_ONE_NODE: int
        TREE_WAS_INVALID_BEFORE_MUTATION: int
