import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class CampaignCriterionErrorEnum(proto.Message):
    class CampaignCriterionError(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        CONCRETE_TYPE_REQUIRED: int
        INVALID_PLACEMENT_URL: int
        CANNOT_EXCLUDE_CRITERIA_TYPE: int
        CANNOT_SET_STATUS_FOR_CRITERIA_TYPE: int
        CANNOT_SET_STATUS_FOR_EXCLUDED_CRITERIA: int
        CANNOT_TARGET_AND_EXCLUDE: int
        TOO_MANY_OPERATIONS: int
        OPERATOR_NOT_SUPPORTED_FOR_CRITERION_TYPE: int
        SHOPPING_CAMPAIGN_SALES_COUNTRY_NOT_SUPPORTED_FOR_SALES_CHANNEL: int
        CANNOT_ADD_EXISTING_FIELD: int
        CANNOT_UPDATE_NEGATIVE_CRITERION: int
        CANNOT_SET_NEGATIVE_KEYWORD_THEME_CONSTANT_CRITERION: int
        INVALID_KEYWORD_THEME_CONSTANT: int
        MISSING_KEYWORD_THEME_CONSTANT_OR_FREE_FORM_KEYWORD_THEME: int
        CANNOT_TARGET_BOTH_PROXIMITY_AND_LOCATION_CRITERIA_FOR_SMART_CAMPAIGN: int
        CANNOT_TARGET_MULTIPLE_PROXIMITY_CRITERIA_FOR_SMART_CAMPAIGN: int
        LOCATION_NOT_LAUNCHED_FOR_LOCAL_SERVICES_CAMPAIGN: int
        LOCATION_INVALID_FOR_LOCAL_SERVICES_CAMPAIGN: int
        CANNOT_TARGET_COUNTRY_FOR_LOCAL_SERVICES_CAMPAIGN: int
        LOCATION_NOT_IN_HOME_COUNTRY_FOR_LOCAL_SERVICES_CAMPAIGN: int
        CANNOT_ADD_OR_REMOVE_LOCATION_FOR_LOCAL_SERVICES_CAMPAIGN: int
        AT_LEAST_ONE_POSITIVE_LOCATION_REQUIRED_FOR_LOCAL_SERVICES_CAMPAIGN: int
        AT_LEAST_ONE_LOCAL_SERVICE_ID_CRITERION_REQUIRED_FOR_LOCAL_SERVICES_CAMPAIGN: int
        LOCAL_SERVICE_ID_NOT_FOUND_FOR_CATEGORY: int
        CANNOT_ATTACH_BRAND_LIST_TO_NON_QUALIFIED_SEARCH_CAMPAIGN: int
        CANNOT_REMOVE_ALL_LOCATIONS_DUE_TO_TOO_MANY_COUNTRY_EXCLUSIONS: int
