import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class CampaignLifecycleGoalErrorEnum(proto.Message):
    class CampaignLifecycleGoalError(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        CAMPAIGN_MISSING: int
        INVALID_CAMPAIGN: int
        CUSTOMER_ACQUISITION_INVALID_OPTIMIZATION_MODE: int
        INCOMPATIBLE_BIDDING_STRATEGY: int
        MISSING_PURCHASE_GOAL: int
        CUSTOMER_ACQUISITION_INVALID_HIGH_LIFETIME_VALUE: int
        CUSTOMER_ACQUISITION_UNSUPPORTED_CAMPAIGN_TYPE: int
        CUSTOMER_ACQUISITION_INVALID_VALUE: int
        CUSTOMER_ACQUISITION_VALUE_MISSING: int
        CUSTOMER_ACQUISITION_MISSING_EXISTING_CUSTOMER_DEFINITION: int
        CUSTOMER_ACQUISITION_MISSING_HIGH_VALUE_CUSTOMER_DEFINITION: int
