import proto
from _typeshed import Incomplete

from google.ads.googleads.v10.enums.types import (
    interaction_event_type as interaction_event_type,
    quality_score_bucket as quality_score_bucket,
)

__protobuf__: Incomplete

class Metrics(proto.Message):
    absolute_top_impression_percentage: Incomplete
    active_view_cpm: Incomplete
    active_view_ctr: Incomplete
    active_view_impressions: Incomplete
    active_view_measurability: Incomplete
    active_view_measurable_cost_micros: Incomplete
    active_view_measurable_impressions: Incomplete
    active_view_viewability: Incomplete
    all_conversions_from_interactions_rate: Incomplete
    all_conversions_value: Incomplete
    all_conversions_value_by_conversion_date: Incomplete
    all_conversions: Incomplete
    all_conversions_by_conversion_date: Incomplete
    all_conversions_value_per_cost: Incomplete
    all_conversions_from_click_to_call: Incomplete
    all_conversions_from_directions: Incomplete
    all_conversions_from_interactions_value_per_interaction: Incomplete
    all_conversions_from_menu: Incomplete
    all_conversions_from_order: Incomplete
    all_conversions_from_other_engagement: Incomplete
    all_conversions_from_store_visit: Incomplete
    all_conversions_from_store_website: Incomplete
    average_cost: Incomplete
    average_cpc: Incomplete
    average_cpe: Incomplete
    average_cpm: Incomplete
    average_cpv: Incomplete
    average_page_views: Incomplete
    average_time_on_site: Incomplete
    benchmark_average_max_cpc: Incomplete
    biddable_app_install_conversions: Incomplete
    biddable_app_post_install_conversions: Incomplete
    benchmark_ctr: Incomplete
    bounce_rate: Incomplete
    clicks: Incomplete
    combined_clicks: Incomplete
    combined_clicks_per_query: Incomplete
    combined_queries: Incomplete
    content_budget_lost_impression_share: Incomplete
    content_impression_share: Incomplete
    conversion_last_received_request_date_time: Incomplete
    conversion_last_conversion_date: Incomplete
    content_rank_lost_impression_share: Incomplete
    conversions_from_interactions_rate: Incomplete
    conversions_value: Incomplete
    conversions_value_by_conversion_date: Incomplete
    conversions_value_per_cost: Incomplete
    conversions_from_interactions_value_per_interaction: Incomplete
    conversions: Incomplete
    conversions_by_conversion_date: Incomplete
    cost_micros: Incomplete
    cost_per_all_conversions: Incomplete
    cost_per_conversion: Incomplete
    cost_per_current_model_attributed_conversion: Incomplete
    cross_device_conversions: Incomplete
    ctr: Incomplete
    current_model_attributed_conversions: Incomplete
    current_model_attributed_conversions_from_interactions_rate: Incomplete
    current_model_attributed_conversions_from_interactions_value_per_interaction: Incomplete
    current_model_attributed_conversions_value: Incomplete
    current_model_attributed_conversions_value_per_cost: Incomplete
    engagement_rate: Incomplete
    engagements: Incomplete
    hotel_average_lead_value_micros: Incomplete
    hotel_commission_rate_micros: Incomplete
    hotel_expected_commission_cost: Incomplete
    hotel_price_difference_percentage: Incomplete
    hotel_eligible_impressions: Incomplete
    historical_creative_quality_score: Incomplete
    historical_landing_page_quality_score: Incomplete
    historical_quality_score: Incomplete
    historical_search_predicted_ctr: Incomplete
    gmail_forwards: Incomplete
    gmail_saves: Incomplete
    gmail_secondary_clicks: Incomplete
    impressions_from_store_reach: Incomplete
    impressions: Incomplete
    interaction_rate: Incomplete
    interactions: Incomplete
    interaction_event_types: Incomplete
    invalid_click_rate: Incomplete
    invalid_clicks: Incomplete
    message_chats: Incomplete
    message_impressions: Incomplete
    message_chat_rate: Incomplete
    mobile_friendly_clicks_percentage: Incomplete
    optimization_score_uplift: Incomplete
    optimization_score_url: Incomplete
    organic_clicks: Incomplete
    organic_clicks_per_query: Incomplete
    organic_impressions: Incomplete
    organic_impressions_per_query: Incomplete
    organic_queries: Incomplete
    percent_new_visitors: Incomplete
    phone_calls: Incomplete
    phone_impressions: Incomplete
    phone_through_rate: Incomplete
    relative_ctr: Incomplete
    search_absolute_top_impression_share: Incomplete
    search_budget_lost_absolute_top_impression_share: Incomplete
    search_budget_lost_impression_share: Incomplete
    search_budget_lost_top_impression_share: Incomplete
    search_click_share: Incomplete
    search_exact_match_impression_share: Incomplete
    search_impression_share: Incomplete
    search_rank_lost_absolute_top_impression_share: Incomplete
    search_rank_lost_impression_share: Incomplete
    search_rank_lost_top_impression_share: Incomplete
    search_top_impression_share: Incomplete
    speed_score: Incomplete
    top_impression_percentage: Incomplete
    valid_accelerated_mobile_pages_clicks_percentage: Incomplete
    value_per_all_conversions: Incomplete
    value_per_all_conversions_by_conversion_date: Incomplete
    value_per_conversion: Incomplete
    value_per_conversions_by_conversion_date: Incomplete
    value_per_current_model_attributed_conversion: Incomplete
    video_quartile_p100_rate: Incomplete
    video_quartile_p25_rate: Incomplete
    video_quartile_p50_rate: Incomplete
    video_quartile_p75_rate: Incomplete
    video_view_rate: Incomplete
    video_views: Incomplete
    view_through_conversions: Incomplete
    sk_ad_network_conversions: Incomplete
