# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class KeywordPlanErrorEnum(google___protobuf___message___Message):
    class KeywordPlanError(object):
        ClosedKeyType = typing___Union[typing_extensions___Literal['UNSPECIFIED'],typing_extensions___Literal['UNKNOWN'],typing_extensions___Literal['BID_MULTIPLIER_OUT_OF_RANGE'],typing_extensions___Literal['BID_TOO_HIGH'],typing_extensions___Literal['BID_TOO_LOW'],typing_extensions___Literal['BID_TOO_MANY_FRACTIONAL_DIGITS'],typing_extensions___Literal['DAILY_BUDGET_TOO_LOW'],typing_extensions___Literal['DAILY_BUDGET_TOO_MANY_FRACTIONAL_DIGITS'],typing_extensions___Literal['INVALID_VALUE'],typing_extensions___Literal['KEYWORD_PLAN_HAS_NO_KEYWORDS'],typing_extensions___Literal['KEYWORD_PLAN_NOT_ENABLED'],typing_extensions___Literal['KEYWORD_PLAN_NOT_FOUND'],typing_extensions___Literal['MISSING_BID'],typing_extensions___Literal['MISSING_FORECAST_PERIOD'],typing_extensions___Literal['INVALID_FORECAST_DATE_RANGE'],typing_extensions___Literal['INVALID_NAME']]
        ClosedValueType = typing___Union[typing_extensions___Literal[0],typing_extensions___Literal[1],typing_extensions___Literal[2],typing_extensions___Literal[3],typing_extensions___Literal[4],typing_extensions___Literal[5],typing_extensions___Literal[6],typing_extensions___Literal[7],typing_extensions___Literal[8],typing_extensions___Literal[9],typing_extensions___Literal[10],typing_extensions___Literal[11],typing_extensions___Literal[13],typing_extensions___Literal[14],typing_extensions___Literal[15],typing_extensions___Literal[16]]
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: ClosedValueType) -> str: ...
        @classmethod
        def Value(cls, name: ClosedKeyType) -> ClosedValueType: ...
        @classmethod
        def keys(cls) -> typing___List[ClosedKeyType]: ...
        @classmethod
        def values(cls) -> typing___List[ClosedValueType]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[ClosedKeyType, ClosedValueType]]: ...
        UNSPECIFIED: typing_extensions___Literal[0]
        UNKNOWN: typing_extensions___Literal[1]
        BID_MULTIPLIER_OUT_OF_RANGE: typing_extensions___Literal[2]
        BID_TOO_HIGH: typing_extensions___Literal[3]
        BID_TOO_LOW: typing_extensions___Literal[4]
        BID_TOO_MANY_FRACTIONAL_DIGITS: typing_extensions___Literal[5]
        DAILY_BUDGET_TOO_LOW: typing_extensions___Literal[6]
        DAILY_BUDGET_TOO_MANY_FRACTIONAL_DIGITS: typing_extensions___Literal[7]
        INVALID_VALUE: typing_extensions___Literal[8]
        KEYWORD_PLAN_HAS_NO_KEYWORDS: typing_extensions___Literal[9]
        KEYWORD_PLAN_NOT_ENABLED: typing_extensions___Literal[10]
        KEYWORD_PLAN_NOT_FOUND: typing_extensions___Literal[11]
        MISSING_BID: typing_extensions___Literal[13]
        MISSING_FORECAST_PERIOD: typing_extensions___Literal[14]
        INVALID_FORECAST_DATE_RANGE: typing_extensions___Literal[15]
        INVALID_NAME: typing_extensions___Literal[16]
    UNSPECIFIED: typing_extensions___Literal[0]
    UNKNOWN: typing_extensions___Literal[1]
    BID_MULTIPLIER_OUT_OF_RANGE: typing_extensions___Literal[2]
    BID_TOO_HIGH: typing_extensions___Literal[3]
    BID_TOO_LOW: typing_extensions___Literal[4]
    BID_TOO_MANY_FRACTIONAL_DIGITS: typing_extensions___Literal[5]
    DAILY_BUDGET_TOO_LOW: typing_extensions___Literal[6]
    DAILY_BUDGET_TOO_MANY_FRACTIONAL_DIGITS: typing_extensions___Literal[7]
    INVALID_VALUE: typing_extensions___Literal[8]
    KEYWORD_PLAN_HAS_NO_KEYWORDS: typing_extensions___Literal[9]
    KEYWORD_PLAN_NOT_ENABLED: typing_extensions___Literal[10]
    KEYWORD_PLAN_NOT_FOUND: typing_extensions___Literal[11]
    MISSING_BID: typing_extensions___Literal[13]
    MISSING_FORECAST_PERIOD: typing_extensions___Literal[14]
    INVALID_FORECAST_DATE_RANGE: typing_extensions___Literal[15]
    INVALID_NAME: typing_extensions___Literal[16]


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> KeywordPlanErrorEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
