"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.ads.google_ads.v5.proto.enums.geo_targeting_type_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class GeographicView(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESOURCE_NAME_FIELD_NUMBER: builtins.int
    LOCATION_TYPE_FIELD_NUMBER: builtins.int
    COUNTRY_CRITERION_ID_FIELD_NUMBER: builtins.int
    resource_name: typing.Text = ...
    location_type: google.ads.google_ads.v5.proto.enums.geo_targeting_type_pb2.GeoTargetingTypeEnum.GeoTargetingType.V = (
        ...
    )
    country_criterion_id: builtins.int = ...
    def __init__(
        self,
        *,
        resource_name: typing.Text = ...,
        location_type: google.ads.google_ads.v5.proto.enums.geo_targeting_type_pb2.GeoTargetingTypeEnum.GeoTargetingType.V = ...,
        country_criterion_id: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "_country_criterion_id",
            b"_country_criterion_id",
            "country_criterion_id",
            b"country_criterion_id",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "_country_criterion_id",
            b"_country_criterion_id",
            "country_criterion_id",
            b"country_criterion_id",
            "location_type",
            b"location_type",
            "resource_name",
            b"resource_name",
        ],
    ) -> None: ...
    def WhichOneof(
        self,
        oneof_group: typing_extensions.Literal[
            "_country_criterion_id", b"_country_criterion_id"
        ],
    ) -> typing_extensions.Literal["country_criterion_id"]: ...

global___GeographicView = GeographicView
