import proto
from _typeshed import Incomplete
from google.ads.googleads.v20.common.types import criteria
from google.ads.googleads.v20.enums.types import ad_destination_type as gage_ad_destination_type, ad_format_type as gage_ad_format_type, ad_network_type as gage_ad_network_type, age_range_type, budget_campaign_association_status as gage_budget_campaign_association_status, click_type as gage_click_type, conversion_action_category as gage_conversion_action_category, conversion_attribution_event_type as gage_conversion_attribution_event_type, conversion_lag_bucket as gage_conversion_lag_bucket, conversion_or_adjustment_lag_bucket as gage_conversion_or_adjustment_lag_bucket, conversion_value_rule_primary_dimension as gage_conversion_value_rule_primary_dimension, converting_user_prior_engagement_type_and_ltv_bucket, day_of_week as gage_day_of_week, device as gage_device, external_conversion_source as gage_external_conversion_source, gender_type, hotel_date_selection_type as gage_hotel_date_selection_type, hotel_price_bucket as gage_hotel_price_bucket, hotel_rate_type as gage_hotel_rate_type, month_of_year as gage_month_of_year, product_channel as gage_product_channel, product_channel_exclusivity as gage_product_channel_exclusivity, product_condition as gage_product_condition, recommendation_type as gage_recommendation_type, search_engine_results_page_type as gage_search_engine_results_page_type, search_term_match_type as gage_search_term_match_type, sk_ad_network_ad_event_type as gage_sk_ad_network_ad_event_type, sk_ad_network_attribution_credit as gage_sk_ad_network_attribution_credit, sk_ad_network_coarse_conversion_value as gage_sk_ad_network_coarse_conversion_value, sk_ad_network_source_type as gage_sk_ad_network_source_type, sk_ad_network_user_type as gage_sk_ad_network_user_type, slot as gage_slot

__protobuf__: Incomplete

class Segments(proto.Message):
    activity_account_id: int
    activity_city: str
    activity_country: str
    activity_rating: int
    activity_state: str
    external_activity_id: str
    ad_destination_type: gage_ad_destination_type.AdDestinationTypeEnum.AdDestinationType
    ad_format_type: gage_ad_format_type.AdFormatTypeEnum.AdFormatType
    ad_network_type: gage_ad_network_type.AdNetworkTypeEnum.AdNetworkType
    ad_group: str
    asset_group: str
    auction_insight_domain: str
    budget_campaign_association_status: BudgetCampaignAssociationStatus
    campaign: str
    click_type: gage_click_type.ClickTypeEnum.ClickType
    conversion_action: str
    conversion_action_category: gage_conversion_action_category.ConversionActionCategoryEnum.ConversionActionCategory
    conversion_action_name: str
    conversion_adjustment: bool
    conversion_attribution_event_type: gage_conversion_attribution_event_type.ConversionAttributionEventTypeEnum.ConversionAttributionEventType
    conversion_lag_bucket: gage_conversion_lag_bucket.ConversionLagBucketEnum.ConversionLagBucket
    conversion_or_adjustment_lag_bucket: gage_conversion_or_adjustment_lag_bucket.ConversionOrAdjustmentLagBucketEnum.ConversionOrAdjustmentLagBucket
    date: str
    day_of_week: gage_day_of_week.DayOfWeekEnum.DayOfWeek
    device: gage_device.DeviceEnum.Device
    external_conversion_source: gage_external_conversion_source.ExternalConversionSourceEnum.ExternalConversionSource
    geo_target_airport: str
    geo_target_canton: str
    geo_target_city: str
    geo_target_country: str
    geo_target_county: str
    geo_target_district: str
    geo_target_metro: str
    geo_target_most_specific_location: str
    geo_target_postal_code: str
    geo_target_province: str
    geo_target_region: str
    geo_target_state: str
    hotel_booking_window_days: int
    hotel_center_id: int
    hotel_check_in_date: str
    hotel_check_in_day_of_week: gage_day_of_week.DayOfWeekEnum.DayOfWeek
    hotel_city: str
    hotel_class: int
    hotel_country: str
    hotel_date_selection_type: gage_hotel_date_selection_type.HotelDateSelectionTypeEnum.HotelDateSelectionType
    hotel_length_of_stay: int
    hotel_rate_rule_id: str
    hotel_rate_type: gage_hotel_rate_type.HotelRateTypeEnum.HotelRateType
    hotel_price_bucket: gage_hotel_price_bucket.HotelPriceBucketEnum.HotelPriceBucket
    hotel_state: str
    hour: int
    interaction_on_this_extension: bool
    keyword: Keyword
    month: str
    month_of_year: gage_month_of_year.MonthOfYearEnum.MonthOfYear
    partner_hotel_id: str
    product_aggregator_id: int
    product_category_level1: str
    product_category_level2: str
    product_category_level3: str
    product_category_level4: str
    product_category_level5: str
    product_brand: str
    product_channel: gage_product_channel.ProductChannelEnum.ProductChannel
    product_channel_exclusivity: gage_product_channel_exclusivity.ProductChannelExclusivityEnum.ProductChannelExclusivity
    product_condition: gage_product_condition.ProductConditionEnum.ProductCondition
    product_country: str
    product_custom_attribute0: str
    product_custom_attribute1: str
    product_custom_attribute2: str
    product_custom_attribute3: str
    product_custom_attribute4: str
    product_feed_label: str
    product_item_id: str
    product_language: str
    product_merchant_id: int
    product_store_id: str
    product_title: str
    product_type_l1: str
    product_type_l2: str
    product_type_l3: str
    product_type_l4: str
    product_type_l5: str
    quarter: str
    travel_destination_city: str
    travel_destination_country: str
    travel_destination_region: str
    recommendation_type: gage_recommendation_type.RecommendationTypeEnum.RecommendationType
    search_engine_results_page_type: gage_search_engine_results_page_type.SearchEngineResultsPageTypeEnum.SearchEngineResultsPageType
    search_subcategory: str
    search_term: str
    search_term_match_type: gage_search_term_match_type.SearchTermMatchTypeEnum.SearchTermMatchType
    slot: gage_slot.SlotEnum.Slot
    conversion_value_rule_primary_dimension: gage_conversion_value_rule_primary_dimension.ConversionValueRulePrimaryDimensionEnum.ConversionValueRulePrimaryDimension
    webpage: str
    week: str
    year: int
    sk_ad_network_fine_conversion_value: int
    sk_ad_network_redistributed_fine_conversion_value: int
    sk_ad_network_user_type: gage_sk_ad_network_user_type.SkAdNetworkUserTypeEnum.SkAdNetworkUserType
    sk_ad_network_ad_event_type: gage_sk_ad_network_ad_event_type.SkAdNetworkAdEventTypeEnum.SkAdNetworkAdEventType
    sk_ad_network_source_app: SkAdNetworkSourceApp
    sk_ad_network_attribution_credit: gage_sk_ad_network_attribution_credit.SkAdNetworkAttributionCreditEnum.SkAdNetworkAttributionCredit
    sk_ad_network_coarse_conversion_value: gage_sk_ad_network_coarse_conversion_value.SkAdNetworkCoarseConversionValueEnum.SkAdNetworkCoarseConversionValue
    sk_ad_network_source_domain: str
    sk_ad_network_source_type: gage_sk_ad_network_source_type.SkAdNetworkSourceTypeEnum.SkAdNetworkSourceType
    sk_ad_network_postback_sequence_index: int
    sk_ad_network_version: str
    asset_interaction_target: AssetInteractionTarget
    new_versus_returning_customers: converting_user_prior_engagement_type_and_ltv_bucket.ConvertingUserPriorEngagementTypeAndLtvBucketEnum.ConvertingUserPriorEngagementTypeAndLtvBucket
    adjusted_age_range: age_range_type.AgeRangeTypeEnum.AgeRangeType
    adjusted_gender: gender_type.GenderTypeEnum.GenderType

class Keyword(proto.Message):
    ad_group_criterion: str
    info: criteria.KeywordInfo

class BudgetCampaignAssociationStatus(proto.Message):
    campaign: str
    status: gage_budget_campaign_association_status.BudgetCampaignAssociationStatusEnum.BudgetCampaignAssociationStatus

class AssetInteractionTarget(proto.Message):
    asset: str
    interaction_on_this_asset: bool

class SkAdNetworkSourceApp(proto.Message):
    sk_ad_network_source_app_id: str
