"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import google.ads.google_ads.v4.proto.resources.customer_client_link_pb2
import grpc

from .customer_client_link_service_pb2 import *

class CustomerClientLinkServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    def GetCustomerClientLink(
        self,
        request: global___GetCustomerClientLinkRequest,
    ) -> google.ads.google_ads.v4.proto.resources.customer_client_link_pb2.CustomerClientLink: ...
    def MutateCustomerClientLink(
        self,
        request: global___MutateCustomerClientLinkRequest,
    ) -> global___MutateCustomerClientLinkResponse: ...

class CustomerClientLinkServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetCustomerClientLink(
        self,
        request: global___GetCustomerClientLinkRequest,
        context: grpc.ServicerContext,
    ) -> google.ads.google_ads.v4.proto.resources.customer_client_link_pb2.CustomerClientLink: ...
    @abc.abstractmethod
    def MutateCustomerClientLink(
        self,
        request: global___MutateCustomerClientLinkRequest,
        context: grpc.ServicerContext,
    ) -> global___MutateCustomerClientLinkResponse: ...

def add_CustomerClientLinkServiceServicer_to_server(
    servicer: CustomerClientLinkServiceServicer, server: grpc.Server
) -> None: ...
