# Stubs for google.ads.google_ads.v1.proto.services.expanded_landing_page_view_service_pb2_grpc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class ExpandedLandingPageViewServiceStub:
    GetExpandedLandingPageView: Any = ...
    def __init__(self, channel: Any) -> None: ...

class ExpandedLandingPageViewServiceServicer:
    def GetExpandedLandingPageView(self, request: Any, context: Any) -> None: ...

def add_ExpandedLandingPageViewServiceServicer_to_server(
    servicer: Any, server: Any
) -> None: ...
