# Stubs for google.ads.google_ads.v1.proto.services.shopping_performance_view_service_pb2_grpc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class ShoppingPerformanceViewServiceStub:
    GetShoppingPerformanceView: Any = ...
    def __init__(self, channel: Any) -> None: ...

class ShoppingPerformanceViewServiceServicer:
    def GetShoppingPerformanceView(self, request: Any, context: Any) -> None: ...

def add_ShoppingPerformanceViewServiceServicer_to_server(
    servicer: Any, server: Any
) -> None: ...
