import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class AssetFieldTypeEnum(proto.Message):
    class AssetFieldType(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        HEADLINE: int
        DESCRIPTION: int
        MANDATORY_AD_TEXT: int
        MARKETING_IMAGE: int
        MEDIA_BUNDLE: int
        YOUTUBE_VIDEO: int
        BOOK_ON_GOOGLE: int
        LEAD_FORM: int
        PROMOTION: int
        CALLOUT: int
        STRUCTURED_SNIPPET: int
        SITELINK: int
        MOBILE_APP: int
        HOTEL_CALLOUT: int
        CALL: int
        PRICE: int
        LONG_HEADLINE: int
        BUSINESS_NAME: int
        SQUARE_MARKETING_IMAGE: int
        PORTRAIT_MARKETING_IMAGE: int
        LOGO: int
        LANDSCAPE_LOGO: int
        VIDEO: int
        CALL_TO_ACTION_SELECTION: int
        AD_IMAGE: int
        BUSINESS_LOGO: int
        HOTEL_PROPERTY: int
        DEMAND_GEN_CAROUSEL_CARD: int
        BUSINESS_MESSAGE: int
        TALL_PORTRAIT_MARKETING_IMAGE: int
