import proto
from _typeshed import Incomplete

__protobuf__: Incomplete

class CampaignPrimaryStatusReasonEnum(proto.Message):
    class CampaignPrimaryStatusReason(proto.Enum):
        UNSPECIFIED: int
        UNKNOWN: int
        CAMPAIGN_REMOVED: int
        CAMPAIGN_PAUSED: int
        CAMPAIGN_PENDING: int
        CAMPAIGN_ENDED: int
        CAMPAIGN_DRAFT: int
        BIDDING_STRATEGY_MISCONFIGURED: int
        BIDDING_STRATEGY_LIMITED: int
        BIDDING_STRATEGY_LEARNING: int
        BIDDING_STRATEGY_CONSTRAINED: int
        BUDGET_CONSTRAINED: int
        BUDGET_MISCONFIGURED: int
        SEARCH_VOLUME_LIMITED: int
        AD_GROUPS_PAUSED: int
        NO_AD_GROUPS: int
        KEYWORDS_PAUSED: int
        NO_KEYWORDS: int
        AD_GROUP_ADS_PAUSED: int
        NO_AD_GROUP_ADS: int
        HAS_ADS_LIMITED_BY_POLICY: int
        HAS_ADS_DISAPPROVED: int
        MOST_ADS_UNDER_REVIEW: int
        MISSING_LEAD_FORM_EXTENSION: int
        MISSING_CALL_EXTENSION: int
        LEAD_FORM_EXTENSION_UNDER_REVIEW: int
        LEAD_FORM_EXTENSION_DISAPPROVED: int
        CALL_EXTENSION_UNDER_REVIEW: int
        CALL_EXTENSION_DISAPPROVED: int
        NO_MOBILE_APPLICATION_AD_GROUP_CRITERIA: int
        CAMPAIGN_GROUP_PAUSED: int
        CAMPAIGN_GROUP_ALL_GROUP_BUDGETS_ENDED: int
        APP_NOT_RELEASED: int
        APP_PARTIALLY_RELEASED: int
        HAS_ASSET_GROUPS_DISAPPROVED: int
        HAS_ASSET_GROUPS_LIMITED_BY_POLICY: int
        MOST_ASSET_GROUPS_UNDER_REVIEW: int
        NO_ASSET_GROUPS: int
        ASSET_GROUPS_PAUSED: int
