# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

from google.ads.google_ads.v6.proto.enums.extension_setting_device_pb2 import (
    ExtensionSettingDeviceEnum as google___ads___googleads___v6___enums___extension_setting_device_pb2___ExtensionSettingDeviceEnum,
)
from google.ads.google_ads.v6.proto.enums.extension_type_pb2 import (
    ExtensionTypeEnum as google___ads___googleads___v6___enums___extension_type_pb2___ExtensionTypeEnum,
)

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class AdGroupExtensionSetting(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    resource_name: typing___Text = ...
    extension_type: google___ads___googleads___v6___enums___extension_type_pb2___ExtensionTypeEnum.ExtensionTypeValue = ...
    ad_group: typing___Text = ...
    extension_feed_items: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        typing___Text
    ] = ...
    device: google___ads___googleads___v6___enums___extension_setting_device_pb2___ExtensionSettingDeviceEnum.ExtensionSettingDeviceValue = ...
    def __init__(
        self,
        *,
        resource_name: typing___Optional[typing___Text] = None,
        extension_type: typing___Optional[
            google___ads___googleads___v6___enums___extension_type_pb2___ExtensionTypeEnum.ExtensionTypeValue
        ] = None,
        ad_group: typing___Optional[typing___Text] = None,
        extension_feed_items: typing___Optional[
            typing___Iterable[typing___Text]
        ] = None,
        device: typing___Optional[
            google___ads___googleads___v6___enums___extension_setting_device_pb2___ExtensionSettingDeviceEnum.ExtensionSettingDeviceValue
        ] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "_ad_group", b"_ad_group", "ad_group", b"ad_group"
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "_ad_group",
            b"_ad_group",
            "ad_group",
            b"ad_group",
            "device",
            b"device",
            "extension_feed_items",
            b"extension_feed_items",
            "extension_type",
            b"extension_type",
            "resource_name",
            b"resource_name",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["_ad_group", b"_ad_group"]
    ) -> typing_extensions___Literal["ad_group"]: ...

type___AdGroupExtensionSetting = AdGroupExtensionSetting
