# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    overload as typing___overload,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

from google.ads.google_ads.v6.proto.enums.billing_setup_status_pb2 import (
    BillingSetupStatusEnum as google___ads___googleads___v6___enums___billing_setup_status_pb2___BillingSetupStatusEnum,
)
from google.ads.google_ads.v6.proto.enums.time_type_pb2 import (
    TimeTypeEnum as google___ads___googleads___v6___enums___time_type_pb2___TimeTypeEnum,
)

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class BillingSetup(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class PaymentsAccountInfo(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        payments_account_id: typing___Text = ...
        payments_account_name: typing___Text = ...
        payments_profile_id: typing___Text = ...
        payments_profile_name: typing___Text = ...
        secondary_payments_profile_id: typing___Text = ...
        def __init__(
            self,
            *,
            payments_account_id: typing___Optional[typing___Text] = None,
            payments_account_name: typing___Optional[typing___Text] = None,
            payments_profile_id: typing___Optional[typing___Text] = None,
            payments_profile_name: typing___Optional[typing___Text] = None,
            secondary_payments_profile_id: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def HasField(
            self,
            field_name: typing_extensions___Literal[
                "_payments_account_id",
                b"_payments_account_id",
                "_payments_account_name",
                b"_payments_account_name",
                "_payments_profile_id",
                b"_payments_profile_id",
                "_payments_profile_name",
                b"_payments_profile_name",
                "_secondary_payments_profile_id",
                b"_secondary_payments_profile_id",
                "payments_account_id",
                b"payments_account_id",
                "payments_account_name",
                b"payments_account_name",
                "payments_profile_id",
                b"payments_profile_id",
                "payments_profile_name",
                b"payments_profile_name",
                "secondary_payments_profile_id",
                b"secondary_payments_profile_id",
            ],
        ) -> builtin___bool: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "_payments_account_id",
                b"_payments_account_id",
                "_payments_account_name",
                b"_payments_account_name",
                "_payments_profile_id",
                b"_payments_profile_id",
                "_payments_profile_name",
                b"_payments_profile_name",
                "_secondary_payments_profile_id",
                b"_secondary_payments_profile_id",
                "payments_account_id",
                b"payments_account_id",
                "payments_account_name",
                b"payments_account_name",
                "payments_profile_id",
                b"payments_profile_id",
                "payments_profile_name",
                b"payments_profile_name",
                "secondary_payments_profile_id",
                b"secondary_payments_profile_id",
            ],
        ) -> None: ...
        @typing___overload
        def WhichOneof(
            self,
            oneof_group: typing_extensions___Literal[
                "_payments_account_id", b"_payments_account_id"
            ],
        ) -> typing_extensions___Literal["payments_account_id"]: ...
        @typing___overload
        def WhichOneof(
            self,
            oneof_group: typing_extensions___Literal[
                "_payments_account_name", b"_payments_account_name"
            ],
        ) -> typing_extensions___Literal["payments_account_name"]: ...
        @typing___overload
        def WhichOneof(
            self,
            oneof_group: typing_extensions___Literal[
                "_payments_profile_id", b"_payments_profile_id"
            ],
        ) -> typing_extensions___Literal["payments_profile_id"]: ...
        @typing___overload
        def WhichOneof(
            self,
            oneof_group: typing_extensions___Literal[
                "_payments_profile_name", b"_payments_profile_name"
            ],
        ) -> typing_extensions___Literal["payments_profile_name"]: ...
        @typing___overload
        def WhichOneof(
            self,
            oneof_group: typing_extensions___Literal[
                "_secondary_payments_profile_id", b"_secondary_payments_profile_id"
            ],
        ) -> typing_extensions___Literal["secondary_payments_profile_id"]: ...
    type___PaymentsAccountInfo = PaymentsAccountInfo

    resource_name: typing___Text = ...
    id: builtin___int = ...
    status: google___ads___googleads___v6___enums___billing_setup_status_pb2___BillingSetupStatusEnum.BillingSetupStatusValue = ...
    payments_account: typing___Text = ...
    start_date_time: typing___Text = ...
    start_time_type: google___ads___googleads___v6___enums___time_type_pb2___TimeTypeEnum.TimeTypeValue = ...
    end_date_time: typing___Text = ...
    end_time_type: google___ads___googleads___v6___enums___time_type_pb2___TimeTypeEnum.TimeTypeValue = ...
    @property
    def payments_account_info(self) -> type___BillingSetup.PaymentsAccountInfo: ...
    def __init__(
        self,
        *,
        resource_name: typing___Optional[typing___Text] = None,
        id: typing___Optional[builtin___int] = None,
        status: typing___Optional[
            google___ads___googleads___v6___enums___billing_setup_status_pb2___BillingSetupStatusEnum.BillingSetupStatusValue
        ] = None,
        payments_account: typing___Optional[typing___Text] = None,
        payments_account_info: typing___Optional[
            type___BillingSetup.PaymentsAccountInfo
        ] = None,
        start_date_time: typing___Optional[typing___Text] = None,
        start_time_type: typing___Optional[
            google___ads___googleads___v6___enums___time_type_pb2___TimeTypeEnum.TimeTypeValue
        ] = None,
        end_date_time: typing___Optional[typing___Text] = None,
        end_time_type: typing___Optional[
            google___ads___googleads___v6___enums___time_type_pb2___TimeTypeEnum.TimeTypeValue
        ] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "_id",
            b"_id",
            "_payments_account",
            b"_payments_account",
            "end_date_time",
            b"end_date_time",
            "end_time",
            b"end_time",
            "end_time_type",
            b"end_time_type",
            "id",
            b"id",
            "payments_account",
            b"payments_account",
            "payments_account_info",
            b"payments_account_info",
            "start_date_time",
            b"start_date_time",
            "start_time",
            b"start_time",
            "start_time_type",
            b"start_time_type",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "_id",
            b"_id",
            "_payments_account",
            b"_payments_account",
            "end_date_time",
            b"end_date_time",
            "end_time",
            b"end_time",
            "end_time_type",
            b"end_time_type",
            "id",
            b"id",
            "payments_account",
            b"payments_account",
            "payments_account_info",
            b"payments_account_info",
            "resource_name",
            b"resource_name",
            "start_date_time",
            b"start_date_time",
            "start_time",
            b"start_time",
            "start_time_type",
            b"start_time_type",
            "status",
            b"status",
        ],
    ) -> None: ...
    @typing___overload
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["_id", b"_id"]
    ) -> typing_extensions___Literal["id"]: ...
    @typing___overload
    def WhichOneof(
        self,
        oneof_group: typing_extensions___Literal[
            "_payments_account", b"_payments_account"
        ],
    ) -> typing_extensions___Literal["payments_account"]: ...
    @typing___overload
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["end_time", b"end_time"]
    ) -> typing_extensions___Literal["end_date_time", "end_time_type"]: ...
    @typing___overload
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["start_time", b"start_time"]
    ) -> typing_extensions___Literal["start_date_time", "start_time_type"]: ...

type___BillingSetup = BillingSetup
