from collections.abc import Generator

import grpc
from _typeshed import Incomplete
from google.protobuf.message import Message

from google.ads.googleads.interceptors import ContinuationType, Interceptor
from google.ads.googleads.interceptors.response_wrappers import (
    _UnaryStreamWrapper,
    _UnaryUnaryWrapper,
)

__all__ = [
    "ExceptionInterceptor",
    "AsyncUnaryUnaryExceptionInterceptor",
    "AsyncUnaryStreamExceptionInterceptor",
]

class ExceptionInterceptor(
    Interceptor, grpc.UnaryUnaryClientInterceptor, grpc.UnaryStreamClientInterceptor
):
    def __init__(self, api_version: str, use_proto_plus: bool = False) -> None: ...
    def intercept_unary_unary(  # type: ignore[override]
        self,
        continuation: ContinuationType,
        client_call_details: grpc.ClientCallDetails,
        request: Message,
    ) -> _UnaryUnaryWrapper: ...
    def intercept_unary_stream(  # type: ignore[override]
        self,
        continuation: ContinuationType,
        client_call_details: grpc.ClientCallDetails,
        request: Message,
    ) -> _UnaryStreamWrapper: ...

class _AsyncUnaryUnaryCallWrapper(grpc.aio.UnaryUnaryCall):
    def __init__(self, call, interceptor, use_proto_plus: bool = False) -> None: ...
    def __await__(self) -> Generator[Incomplete, Incomplete, Incomplete]: ...
    def cancel(self): ...
    def cancelled(self): ...
    def done(self): ...
    def add_done_callback(self, callback) -> None: ...
    def code(self): ...
    def details(self): ...
    def initial_metadata(self): ...
    def trailing_metadata(self): ...
    def time_remaining(self): ...
    async def wait_for_connection(self): ...

class _AsyncUnaryStreamCallWrapper(grpc.aio.UnaryStreamCall):
    def __init__(self, call, interceptor, use_proto_plus: bool = False) -> None: ...
    def __aiter__(self): ...
    def cancel(self): ...
    def cancelled(self): ...
    def done(self): ...
    def add_done_callback(self, callback) -> None: ...
    def code(self): ...
    def details(self): ...
    def initial_metadata(self): ...
    def trailing_metadata(self): ...
    def time_remaining(self): ...
    async def wait_for_connection(self): ...
    async def read(self): ...

class _AsyncExceptionInterceptor(
    Interceptor,
    grpc.aio.UnaryUnaryClientInterceptor,
    grpc.aio.UnaryStreamClientInterceptor,
):
    def __init__(self, api_version: str, use_proto_plus: bool = False) -> None: ...
    async def intercept_unary_unary(
        self, continuation, client_call_details, request
    ) -> _AsyncUnaryUnaryCallWrapper: ...
    async def intercept_unary_stream(
        self, continuation, client_call_details, request
    ) -> _AsyncUnaryStreamCallWrapper: ...

class AsyncUnaryUnaryExceptionInterceptor(
    _AsyncExceptionInterceptor, grpc.aio.UnaryUnaryClientInterceptor
): ...
class AsyncUnaryStreamExceptionInterceptor(
    _AsyncExceptionInterceptor, grpc.aio.UnaryStreamClientInterceptor
): ...
