from types import SimpleNamespace, TracebackType
from typing import Any, Callable, Iterator

import grpc
from google.protobuf.message import Message as ProtobufMessageType

from google.ads.googleads.interceptors import MetadataType as MetadataType

class _UnaryStreamWrapper(grpc.Call, grpc.Future):
    def __init__(
        self,
        underlay_call: grpc.Call | grpc.Future,
        failure_handler: Callable[[grpc.Call | grpc.Future], grpc.Call],
        use_proto_plus: bool = False,
    ) -> None: ...
    def initial_metadata(self) -> MetadataType: ...  # type: ignore[override]
    def trailing_metadata(self) -> MetadataType: ...  # type: ignore[override]
    def code(self) -> grpc.StatusCode: ...
    def details(self) -> str: ...
    def debug_error_string(self) -> str: ...
    def cancelled(self) -> bool: ...
    def running(self) -> bool: ...
    def done(self) -> bool: ...
    def result(self, timeout: float | None = None) -> ProtobufMessageType: ...
    def exception(self, timeout: float | None = None) -> grpc.RpcError | None: ...
    def traceback(self, timeout: float | None = None) -> TracebackType | None: ...
    def add_done_callback(self, fn: Callable[[grpc.Future], Any]) -> None: ...
    def add_callback(self, callback: Callable[[grpc.Future], Any]) -> None: ...  # type: ignore[override]
    def is_active(self) -> bool: ...
    def time_remaining(self) -> float | None: ...  # type: ignore[override]
    def cancel(self) -> bool: ...
    def __iter__(self) -> Iterator[ProtobufMessageType]: ...
    def __next__(self) -> ProtobufMessageType: ...
    def get_cache(self) -> SimpleNamespace: ...

class _UnaryUnaryWrapper(grpc.Call, grpc.Future):
    def __init__(
        self, underlay_call: grpc.Call | grpc.Future, use_proto_plus: bool = False
    ) -> None: ...
    def initial_metadata(self) -> MetadataType: ...  # type: ignore[override]
    def trailing_metadata(self) -> MetadataType: ...  # type: ignore[override]
    def code(self) -> grpc.StatusCode: ...
    def details(self) -> str: ...
    def debug_error_string(self) -> str: ...
    def cancelled(self) -> bool: ...
    def running(self) -> bool: ...
    def done(self) -> bool: ...
    def result(self, timeout: float | None = None) -> ProtobufMessageType: ...
    def exception(self, timeout: float | None = None) -> grpc.RpcError | None: ...
    def traceback(self, timeout: float | None = None) -> TracebackType | None: ...
    def add_done_callback(self, fn: Callable[[grpc.Future], Any]) -> None: ...
    def add_callback(self, callback: Callable[[grpc.Future], Any]) -> None: ...  # type: ignore[override]
    def is_active(self) -> bool: ...
    def time_remaining(self) -> float | None: ...  # type: ignore[override]
    def cancel(self) -> bool: ...
    def __iter__(self) -> Iterator[ProtobufMessageType]: ...
    def __next__(self) -> ProtobufMessageType: ...
