import proto
from _typeshed import Incomplete
from google.ads.googleads.v18.enums.types import ad_customizer_placeholder_field, affiliate_location_placeholder_field, app_placeholder_field, call_placeholder_field, callout_placeholder_field, custom_placeholder_field, dsa_page_feed_criterion_field, education_placeholder_field, feed_mapping_criterion_type, feed_mapping_status, flight_placeholder_field, hotel_placeholder_field, image_placeholder_field, job_placeholder_field, local_placeholder_field, location_extension_targeting_criterion_field, location_placeholder_field, message_placeholder_field, placeholder_type as gage_placeholder_type, price_placeholder_field, promotion_placeholder_field, real_estate_placeholder_field, sitelink_placeholder_field, structured_snippet_placeholder_field, travel_placeholder_field
from typing import MutableSequence

__protobuf__: Incomplete

class FeedMapping(proto.Message):
    resource_name: str
    feed: str
    attribute_field_mappings: MutableSequence['AttributeFieldMapping']
    status: feed_mapping_status.FeedMappingStatusEnum.FeedMappingStatus
    placeholder_type: gage_placeholder_type.PlaceholderTypeEnum.PlaceholderType
    criterion_type: feed_mapping_criterion_type.FeedMappingCriterionTypeEnum.FeedMappingCriterionType

class AttributeFieldMapping(proto.Message):
    feed_attribute_id: int
    field_id: int
    sitelink_field: sitelink_placeholder_field.SitelinkPlaceholderFieldEnum.SitelinkPlaceholderField
    call_field: call_placeholder_field.CallPlaceholderFieldEnum.CallPlaceholderField
    app_field: app_placeholder_field.AppPlaceholderFieldEnum.AppPlaceholderField
    location_field: location_placeholder_field.LocationPlaceholderFieldEnum.LocationPlaceholderField
    affiliate_location_field: affiliate_location_placeholder_field.AffiliateLocationPlaceholderFieldEnum.AffiliateLocationPlaceholderField
    callout_field: callout_placeholder_field.CalloutPlaceholderFieldEnum.CalloutPlaceholderField
    structured_snippet_field: structured_snippet_placeholder_field.StructuredSnippetPlaceholderFieldEnum.StructuredSnippetPlaceholderField
    message_field: message_placeholder_field.MessagePlaceholderFieldEnum.MessagePlaceholderField
    price_field: price_placeholder_field.PricePlaceholderFieldEnum.PricePlaceholderField
    promotion_field: promotion_placeholder_field.PromotionPlaceholderFieldEnum.PromotionPlaceholderField
    ad_customizer_field: ad_customizer_placeholder_field.AdCustomizerPlaceholderFieldEnum.AdCustomizerPlaceholderField
    dsa_page_feed_field: dsa_page_feed_criterion_field.DsaPageFeedCriterionFieldEnum.DsaPageFeedCriterionField
    location_extension_targeting_field: location_extension_targeting_criterion_field.LocationExtensionTargetingCriterionFieldEnum.LocationExtensionTargetingCriterionField
    education_field: education_placeholder_field.EducationPlaceholderFieldEnum.EducationPlaceholderField
    flight_field: flight_placeholder_field.FlightPlaceholderFieldEnum.FlightPlaceholderField
    custom_field: custom_placeholder_field.CustomPlaceholderFieldEnum.CustomPlaceholderField
    hotel_field: hotel_placeholder_field.HotelPlaceholderFieldEnum.HotelPlaceholderField
    real_estate_field: real_estate_placeholder_field.RealEstatePlaceholderFieldEnum.RealEstatePlaceholderField
    travel_field: travel_placeholder_field.TravelPlaceholderFieldEnum.TravelPlaceholderField
    local_field: local_placeholder_field.LocalPlaceholderFieldEnum.LocalPlaceholderField
    job_field: job_placeholder_field.JobPlaceholderFieldEnum.JobPlaceholderField
    image_field: image_placeholder_field.ImagePlaceholderFieldEnum.ImagePlaceholderField
