from .transports.base import CampaignLifecycleGoalServiceTransport
from _typeshed import Incomplete
from google.ads.googleads.v20.services.types import campaign_lifecycle_goal_service
from google.api_core import client_options as client_options_lib, gapic_v1, retry as retries
from google.auth import credentials as ga_credentials
from typing import Callable, Dict, Sequence, Tuple, Type

__all__ = ['CampaignLifecycleGoalServiceClient']

class CampaignLifecycleGoalServiceClientMeta(type):
    def get_transport_class(cls, label: str | None = None) -> Type[CampaignLifecycleGoalServiceTransport]: ...

class CampaignLifecycleGoalServiceClient(metaclass=CampaignLifecycleGoalServiceClientMeta):
    DEFAULT_ENDPOINT: str
    DEFAULT_MTLS_ENDPOINT: Incomplete
    @classmethod
    def from_service_account_info(cls, info: dict, *args, **kwargs): ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args, **kwargs): ...
    from_service_account_json = from_service_account_file
    @property
    def transport(self) -> CampaignLifecycleGoalServiceTransport: ...
    @staticmethod
    def campaign_path(customer_id: str, campaign_id: str) -> str: ...
    @staticmethod
    def parse_campaign_path(path: str) -> Dict[str, str]: ...
    @staticmethod
    def campaign_lifecycle_goal_path(customer_id: str, campaign_id: str) -> str: ...
    @staticmethod
    def parse_campaign_lifecycle_goal_path(path: str) -> Dict[str, str]: ...
    @staticmethod
    def common_billing_account_path(billing_account: str) -> str: ...
    @staticmethod
    def parse_common_billing_account_path(path: str) -> Dict[str, str]: ...
    @staticmethod
    def common_folder_path(folder: str) -> str: ...
    @staticmethod
    def parse_common_folder_path(path: str) -> Dict[str, str]: ...
    @staticmethod
    def common_organization_path(organization: str) -> str: ...
    @staticmethod
    def parse_common_organization_path(path: str) -> Dict[str, str]: ...
    @staticmethod
    def common_project_path(project: str) -> str: ...
    @staticmethod
    def parse_common_project_path(path: str) -> Dict[str, str]: ...
    @staticmethod
    def common_location_path(project: str, location: str) -> str: ...
    @staticmethod
    def parse_common_location_path(path: str) -> Dict[str, str]: ...
    @classmethod
    def get_mtls_endpoint_and_cert_source(cls, client_options: client_options_lib.ClientOptions | None = None): ...
    @property
    def api_endpoint(self): ...
    @property
    def universe_domain(self) -> str: ...
    def __init__(self, *, credentials: ga_credentials.Credentials | None = None, transport: str | CampaignLifecycleGoalServiceTransport | Callable[..., CampaignLifecycleGoalServiceTransport] | None = None, client_options: client_options_lib.ClientOptions | dict | None = None, client_info: gapic_v1.client_info.ClientInfo = ...) -> None: ...
    def configure_campaign_lifecycle_goals(self, request: campaign_lifecycle_goal_service.ConfigureCampaignLifecycleGoalsRequest | dict | None = None, *, customer_id: str | None = None, operation: campaign_lifecycle_goal_service.CampaignLifecycleGoalOperation | None = None, retry: retries.Retry | gapic_v1.method._MethodDefault = ..., timeout: float | object = ..., metadata: Sequence[Tuple[str, str | bytes]] = ()) -> campaign_lifecycle_goal_service.ConfigureCampaignLifecycleGoalsResponse: ...
    def __enter__(self) -> CampaignLifecycleGoalServiceClient: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
