from typing import Any

import grpc
import requests

class ResumableUploadErrorAdapter(grpc.RpcError, grpc.Call):
    def __init__(
        self, response: requests.Response, mapped_grpc_code: grpc.StatusCode
    ) -> None: ...
    def code(self) -> grpc.StatusCode: ...
    def details(self) -> str: ...
    def initial_metadata(self) -> Any: ...
    def trailing_metadata(self) -> Any: ...
    def is_active(self) -> bool: ...
    def time_remaining(self) -> float | None: ...  # type: ignore[override]
    def cancel(self) -> None: ...
    def add_callback(self, callback: Any) -> None: ...  # type: ignore[override]

def raise_formatted_ads_exception(response: requests.Response): ...
def raise_formatted_for_status(response: requests.Response): ...
