# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class FeedItemQualityDisapprovalReasonEnum(google___protobuf___message___Message):
    class FeedItemQualityDisapprovalReason(object):
        ClosedKeyType = typing___Union[typing_extensions___Literal['UNSPECIFIED'],typing_extensions___Literal['UNKNOWN'],typing_extensions___Literal['PRICE_TABLE_REPETITIVE_HEADERS'],typing_extensions___Literal['PRICE_TABLE_REPETITIVE_DESCRIPTION'],typing_extensions___Literal['PRICE_TABLE_INCONSISTENT_ROWS'],typing_extensions___Literal['PRICE_DESCRIPTION_HAS_PRICE_QUALIFIERS'],typing_extensions___Literal['PRICE_UNSUPPORTED_LANGUAGE'],typing_extensions___Literal['PRICE_TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH'],typing_extensions___Literal['PRICE_TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT'],typing_extensions___Literal['PRICE_TABLE_ROW_DESCRIPTION_NOT_RELEVANT'],typing_extensions___Literal['PRICE_TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT'],typing_extensions___Literal['PRICE_TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE'],typing_extensions___Literal['PRICE_TABLE_ROW_UNRATEABLE'],typing_extensions___Literal['PRICE_TABLE_ROW_PRICE_INVALID'],typing_extensions___Literal['PRICE_TABLE_ROW_URL_INVALID'],typing_extensions___Literal['PRICE_HEADER_OR_DESCRIPTION_HAS_PRICE'],typing_extensions___Literal['STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED'],typing_extensions___Literal['STRUCTURED_SNIPPETS_REPEATED_VALUES'],typing_extensions___Literal['STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES'],typing_extensions___Literal['STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT']]
        ClosedValueType = typing___Union[typing_extensions___Literal[0],typing_extensions___Literal[1],typing_extensions___Literal[2],typing_extensions___Literal[3],typing_extensions___Literal[4],typing_extensions___Literal[5],typing_extensions___Literal[6],typing_extensions___Literal[7],typing_extensions___Literal[8],typing_extensions___Literal[9],typing_extensions___Literal[10],typing_extensions___Literal[11],typing_extensions___Literal[12],typing_extensions___Literal[13],typing_extensions___Literal[14],typing_extensions___Literal[15],typing_extensions___Literal[16],typing_extensions___Literal[17],typing_extensions___Literal[18],typing_extensions___Literal[19]]
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: ClosedValueType) -> str: ...
        @classmethod
        def Value(cls, name: ClosedKeyType) -> ClosedValueType: ...
        @classmethod
        def keys(cls) -> typing___List[ClosedKeyType]: ...
        @classmethod
        def values(cls) -> typing___List[ClosedValueType]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[ClosedKeyType, ClosedValueType]]: ...
        UNSPECIFIED: typing_extensions___Literal[0]
        UNKNOWN: typing_extensions___Literal[1]
        PRICE_TABLE_REPETITIVE_HEADERS: typing_extensions___Literal[2]
        PRICE_TABLE_REPETITIVE_DESCRIPTION: typing_extensions___Literal[3]
        PRICE_TABLE_INCONSISTENT_ROWS: typing_extensions___Literal[4]
        PRICE_DESCRIPTION_HAS_PRICE_QUALIFIERS: typing_extensions___Literal[5]
        PRICE_UNSUPPORTED_LANGUAGE: typing_extensions___Literal[6]
        PRICE_TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH: typing_extensions___Literal[7]
        PRICE_TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT: typing_extensions___Literal[8]
        PRICE_TABLE_ROW_DESCRIPTION_NOT_RELEVANT: typing_extensions___Literal[9]
        PRICE_TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT: typing_extensions___Literal[10]
        PRICE_TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE: typing_extensions___Literal[11]
        PRICE_TABLE_ROW_UNRATEABLE: typing_extensions___Literal[12]
        PRICE_TABLE_ROW_PRICE_INVALID: typing_extensions___Literal[13]
        PRICE_TABLE_ROW_URL_INVALID: typing_extensions___Literal[14]
        PRICE_HEADER_OR_DESCRIPTION_HAS_PRICE: typing_extensions___Literal[15]
        STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED: typing_extensions___Literal[16]
        STRUCTURED_SNIPPETS_REPEATED_VALUES: typing_extensions___Literal[17]
        STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES: typing_extensions___Literal[18]
        STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT: typing_extensions___Literal[19]
    UNSPECIFIED: typing_extensions___Literal[0]
    UNKNOWN: typing_extensions___Literal[1]
    PRICE_TABLE_REPETITIVE_HEADERS: typing_extensions___Literal[2]
    PRICE_TABLE_REPETITIVE_DESCRIPTION: typing_extensions___Literal[3]
    PRICE_TABLE_INCONSISTENT_ROWS: typing_extensions___Literal[4]
    PRICE_DESCRIPTION_HAS_PRICE_QUALIFIERS: typing_extensions___Literal[5]
    PRICE_UNSUPPORTED_LANGUAGE: typing_extensions___Literal[6]
    PRICE_TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH: typing_extensions___Literal[7]
    PRICE_TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT: typing_extensions___Literal[8]
    PRICE_TABLE_ROW_DESCRIPTION_NOT_RELEVANT: typing_extensions___Literal[9]
    PRICE_TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT: typing_extensions___Literal[10]
    PRICE_TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE: typing_extensions___Literal[11]
    PRICE_TABLE_ROW_UNRATEABLE: typing_extensions___Literal[12]
    PRICE_TABLE_ROW_PRICE_INVALID: typing_extensions___Literal[13]
    PRICE_TABLE_ROW_URL_INVALID: typing_extensions___Literal[14]
    PRICE_HEADER_OR_DESCRIPTION_HAS_PRICE: typing_extensions___Literal[15]
    STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED: typing_extensions___Literal[16]
    STRUCTURED_SNIPPETS_REPEATED_VALUES: typing_extensions___Literal[17]
    STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES: typing_extensions___Literal[18]
    STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT: typing_extensions___Literal[19]


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> FeedItemQualityDisapprovalReasonEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
