# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class ManagerLinkStatusEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ManagerLinkStatus(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> ManagerLinkStatusEnum.ManagerLinkStatus: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[ManagerLinkStatusEnum.ManagerLinkStatus]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, ManagerLinkStatusEnum.ManagerLinkStatus]]: ...
        UNSPECIFIED = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 0)
        UNKNOWN = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 1)
        ACTIVE = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 2)
        INACTIVE = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 3)
        PENDING = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 4)
        REFUSED = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 5)
        CANCELED = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 6)
    UNSPECIFIED = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 0)
    UNKNOWN = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 1)
    ACTIVE = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 2)
    INACTIVE = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 3)
    PENDING = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 4)
    REFUSED = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 5)
    CANCELED = typing___cast(ManagerLinkStatusEnum.ManagerLinkStatus, 6)


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ManagerLinkStatusEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
