# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class TrackingCodeTypeEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class TrackingCodeType(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> TrackingCodeTypeEnum.TrackingCodeType: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[TrackingCodeTypeEnum.TrackingCodeType]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, TrackingCodeTypeEnum.TrackingCodeType]]: ...
        UNSPECIFIED = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 0)
        UNKNOWN = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 1)
        WEBPAGE = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 2)
        WEBPAGE_ONCLICK = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 3)
        CLICK_TO_CALL = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 4)
    UNSPECIFIED = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 0)
    UNKNOWN = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 1)
    WEBPAGE = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 2)
    WEBPAGE_ONCLICK = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 3)
    CLICK_TO_CALL = typing___cast(TrackingCodeTypeEnum.TrackingCodeType, 4)


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TrackingCodeTypeEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
