# Stubs for google.ads.google_ads.v2.proto.services.customer_client_service_pb2_grpc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class CustomerClientServiceStub:
    GetCustomerClient: Any = ...
    def __init__(self, channel: Any) -> None: ...

class CustomerClientServiceServicer:
    def GetCustomerClient(self, request: Any, context: Any) -> None: ...

def add_CustomerClientServiceServicer_to_server(servicer: Any, server: Any) -> None: ...
