import proto
from _typeshed import Incomplete
from google.ads.googleads.v18.common.types import metrics as gagc_metrics, segments as gagc_segments
from google.ads.googleads.v18.enums.types import response_content_type as gage_response_content_type, summary_row_setting as gage_summary_row_setting
from google.ads.googleads.v18.resources.types import accessible_bidding_strategy as gagr_accessible_bidding_strategy, account_budget as gagr_account_budget, account_budget_proposal as gagr_account_budget_proposal, account_link as gagr_account_link, ad as gagr_ad, ad_group as gagr_ad_group, ad_group_ad as gagr_ad_group_ad, ad_group_ad_asset_combination_view as gagr_ad_group_ad_asset_combination_view, ad_group_ad_asset_view as gagr_ad_group_ad_asset_view, ad_group_ad_label as gagr_ad_group_ad_label, ad_group_asset as gagr_ad_group_asset, ad_group_asset_set as gagr_ad_group_asset_set, ad_group_audience_view as gagr_ad_group_audience_view, ad_group_bid_modifier as gagr_ad_group_bid_modifier, ad_group_criterion as gagr_ad_group_criterion, ad_group_criterion_customizer as gagr_ad_group_criterion_customizer, ad_group_criterion_label as gagr_ad_group_criterion_label, ad_group_criterion_simulation as gagr_ad_group_criterion_simulation, ad_group_customizer as gagr_ad_group_customizer, ad_group_extension_setting as gagr_ad_group_extension_setting, ad_group_feed as gagr_ad_group_feed, ad_group_label as gagr_ad_group_label, ad_group_simulation as gagr_ad_group_simulation, ad_parameter as gagr_ad_parameter, ad_schedule_view as gagr_ad_schedule_view, age_range_view as gagr_age_range_view, android_privacy_shared_key_google_ad_group as gagr_android_privacy_shared_key_google_ad_group, android_privacy_shared_key_google_campaign as gagr_android_privacy_shared_key_google_campaign, android_privacy_shared_key_google_network_type as gagr_android_privacy_shared_key_google_network_type, asset as gagr_asset, asset_field_type_view as gagr_asset_field_type_view, asset_group as gagr_asset_group, asset_group_asset as gagr_asset_group_asset, asset_group_listing_group_filter as gagr_asset_group_listing_group_filter, asset_group_product_group_view as gagr_asset_group_product_group_view, asset_group_signal as gagr_asset_group_signal, asset_group_top_combination_view as gagr_asset_group_top_combination_view, asset_set as gagr_asset_set, asset_set_asset as gagr_asset_set_asset, asset_set_type_view as gagr_asset_set_type_view, audience as gagr_audience, batch_job as gagr_batch_job, bidding_data_exclusion as gagr_bidding_data_exclusion, bidding_seasonality_adjustment as gagr_bidding_seasonality_adjustment, bidding_strategy as gagr_bidding_strategy, bidding_strategy_simulation as gagr_bidding_strategy_simulation, billing_setup as gagr_billing_setup, call_view as gagr_call_view, campaign as gagr_campaign, campaign_aggregate_asset_view as gagr_campaign_aggregate_asset_view, campaign_asset as gagr_campaign_asset, campaign_asset_set as gagr_campaign_asset_set, campaign_audience_view as gagr_campaign_audience_view, campaign_bid_modifier as gagr_campaign_bid_modifier, campaign_budget as gagr_campaign_budget, campaign_conversion_goal as gagr_campaign_conversion_goal, campaign_criterion as gagr_campaign_criterion, campaign_customizer as gagr_campaign_customizer, campaign_draft as gagr_campaign_draft, campaign_extension_setting as gagr_campaign_extension_setting, campaign_feed as gagr_campaign_feed, campaign_group as gagr_campaign_group, campaign_label as gagr_campaign_label, campaign_lifecycle_goal as gagr_campaign_lifecycle_goal, campaign_search_term_insight as gagr_campaign_search_term_insight, campaign_shared_set as gagr_campaign_shared_set, campaign_simulation as gagr_campaign_simulation, carrier_constant as gagr_carrier_constant, change_event as gagr_change_event, change_status as gagr_change_status, channel_aggregate_asset_view as gagr_channel_aggregate_asset_view, click_view as gagr_click_view, combined_audience as gagr_combined_audience, content_criterion_view as gagr_content_criterion_view, conversion_action as gagr_conversion_action, conversion_custom_variable as gagr_conversion_custom_variable, conversion_goal_campaign_config as gagr_conversion_goal_campaign_config, conversion_value_rule as gagr_conversion_value_rule, conversion_value_rule_set as gagr_conversion_value_rule_set, currency_constant as gagr_currency_constant, custom_audience as gagr_custom_audience, custom_conversion_goal as gagr_custom_conversion_goal, custom_interest as gagr_custom_interest, customer as gagr_customer, customer_asset as gagr_customer_asset, customer_asset_set as gagr_customer_asset_set, customer_client as gagr_customer_client, customer_client_link as gagr_customer_client_link, customer_conversion_goal as gagr_customer_conversion_goal, customer_customizer as gagr_customer_customizer, customer_extension_setting as gagr_customer_extension_setting, customer_feed as gagr_customer_feed, customer_label as gagr_customer_label, customer_lifecycle_goal as gagr_customer_lifecycle_goal, customer_manager_link as gagr_customer_manager_link, customer_negative_criterion as gagr_customer_negative_criterion, customer_search_term_insight as gagr_customer_search_term_insight, customer_user_access as gagr_customer_user_access, customer_user_access_invitation as gagr_customer_user_access_invitation, customizer_attribute as gagr_customizer_attribute, data_link as gagr_data_link, detail_placement_view as gagr_detail_placement_view, detailed_demographic as gagr_detailed_demographic, display_keyword_view as gagr_display_keyword_view, distance_view as gagr_distance_view, domain_category as gagr_domain_category, dynamic_search_ads_search_term_view as gagr_dynamic_search_ads_search_term_view, expanded_landing_page_view as gagr_expanded_landing_page_view, experiment as gagr_experiment, experiment_arm as gagr_experiment_arm, extension_feed_item as gagr_extension_feed_item, feed as gagr_feed, feed_item as gagr_feed_item, feed_item_set as gagr_feed_item_set, feed_item_set_link as gagr_feed_item_set_link, feed_item_target as gagr_feed_item_target, feed_mapping as gagr_feed_mapping, feed_placeholder_view as gagr_feed_placeholder_view, gender_view as gagr_gender_view, geo_target_constant as gagr_geo_target_constant, geographic_view as gagr_geographic_view, group_placement_view as gagr_group_placement_view, hotel_group_view as gagr_hotel_group_view, hotel_performance_view as gagr_hotel_performance_view, hotel_reconciliation as gagr_hotel_reconciliation, income_range_view as gagr_income_range_view, keyword_plan as gagr_keyword_plan, keyword_plan_ad_group as gagr_keyword_plan_ad_group, keyword_plan_ad_group_keyword as gagr_keyword_plan_ad_group_keyword, keyword_plan_campaign as gagr_keyword_plan_campaign, keyword_plan_campaign_keyword as gagr_keyword_plan_campaign_keyword, keyword_theme_constant as gagr_keyword_theme_constant, keyword_view as gagr_keyword_view, label as gagr_label, landing_page_view as gagr_landing_page_view, language_constant as gagr_language_constant, lead_form_submission_data as gagr_lead_form_submission_data, life_event as gagr_life_event, local_services_employee as gagr_local_services_employee, local_services_lead as gagr_local_services_lead, local_services_lead_conversation as gagr_local_services_lead_conversation, local_services_verification_artifact as gagr_local_services_verification_artifact, location_view as gagr_location_view, managed_placement_view as gagr_managed_placement_view, media_file as gagr_media_file, mobile_app_category_constant as gagr_mobile_app_category_constant, mobile_device_constant as gagr_mobile_device_constant, offline_conversion_upload_client_summary as gagr_offline_conversion_upload_client_summary, offline_conversion_upload_conversion_action_summary as gagr_offline_conversion_upload_conversion_action_summary, offline_user_data_job as gagr_offline_user_data_job, operating_system_version_constant as gagr_operating_system_version_constant, paid_organic_search_term_view as gagr_paid_organic_search_term_view, parental_status_view as gagr_parental_status_view, per_store_view as gagr_per_store_view, performance_max_placement_view as gagr_performance_max_placement_view, product_category_constant as gagr_product_category_constant, product_group_view as gagr_product_group_view, product_link as gagr_product_link, product_link_invitation as gagr_product_link_invitation, qualifying_question as gagr_qualifying_question, recommendation as gagr_recommendation, recommendation_subscription as gagr_recommendation_subscription, remarketing_action as gagr_remarketing_action, search_term_view as gagr_search_term_view, shared_criterion as gagr_shared_criterion, shared_set as gagr_shared_set, shopping_performance_view as gagr_shopping_performance_view, shopping_product as gagr_shopping_product, smart_campaign_search_term_view as gagr_smart_campaign_search_term_view, smart_campaign_setting as gagr_smart_campaign_setting, third_party_app_analytics_link as gagr_third_party_app_analytics_link, topic_constant as gagr_topic_constant, topic_view as gagr_topic_view, travel_activity_group_view as gagr_travel_activity_group_view, travel_activity_performance_view as gagr_travel_activity_performance_view, user_interest as gagr_user_interest, user_list as gagr_user_list, user_list_customer_type as gagr_user_list_customer_type, user_location_view as gagr_user_location_view, video as gagr_video, webpage_view as gagr_webpage_view
from google.ads.googleads.v18.services.types import ad_group_ad_label_service, ad_group_ad_service, ad_group_asset_service, ad_group_bid_modifier_service, ad_group_criterion_customizer_service, ad_group_criterion_label_service, ad_group_criterion_service, ad_group_customizer_service, ad_group_extension_setting_service, ad_group_feed_service, ad_group_label_service, ad_group_service, ad_parameter_service, ad_service, asset_group_asset_service, asset_group_listing_group_filter_service, asset_group_service, asset_group_signal_service, asset_service, asset_set_asset_service, asset_set_service, audience_service, bidding_data_exclusion_service, bidding_seasonality_adjustment_service, bidding_strategy_service, campaign_asset_service, campaign_asset_set_service, campaign_bid_modifier_service, campaign_budget_service, campaign_conversion_goal_service, campaign_criterion_service, campaign_customizer_service, campaign_draft_service, campaign_extension_setting_service, campaign_feed_service, campaign_group_service, campaign_label_service, campaign_service, campaign_shared_set_service, conversion_action_service, conversion_custom_variable_service, conversion_goal_campaign_config_service, conversion_value_rule_service, conversion_value_rule_set_service, custom_conversion_goal_service, customer_asset_service, customer_conversion_goal_service, customer_customizer_service, customer_extension_setting_service, customer_feed_service, customer_label_service, customer_negative_criterion_service, customer_service, customizer_attribute_service, experiment_arm_service, experiment_service, extension_feed_item_service, feed_item_service, feed_item_set_link_service, feed_item_set_service, feed_item_target_service, feed_mapping_service, feed_service, keyword_plan_ad_group_keyword_service, keyword_plan_ad_group_service, keyword_plan_campaign_keyword_service, keyword_plan_campaign_service, keyword_plan_service, label_service, recommendation_subscription_service, remarketing_action_service, shared_criterion_service, shared_set_service, smart_campaign_setting_service, user_list_service
from google.protobuf import field_mask_pb2
from google.rpc import status_pb2
from typing import MutableSequence

__protobuf__: Incomplete

class SearchGoogleAdsRequest(proto.Message):
    customer_id: str
    query: str
    page_token: str
    page_size: int
    validate_only: bool
    search_settings: SearchSettings

class SearchGoogleAdsResponse(proto.Message):
    @property
    def raw_page(self): ...
    results: MutableSequence['GoogleAdsRow']
    next_page_token: str
    total_results_count: int
    field_mask: field_mask_pb2.FieldMask
    summary_row: GoogleAdsRow
    query_resource_consumption: int

class SearchGoogleAdsStreamRequest(proto.Message):
    customer_id: str
    query: str
    summary_row_setting: gage_summary_row_setting.SummaryRowSettingEnum.SummaryRowSetting

class SearchGoogleAdsStreamResponse(proto.Message):
    results: MutableSequence['GoogleAdsRow']
    field_mask: field_mask_pb2.FieldMask
    summary_row: GoogleAdsRow
    request_id: str
    query_resource_consumption: int

class GoogleAdsRow(proto.Message):
    account_budget: gagr_account_budget.AccountBudget
    account_budget_proposal: gagr_account_budget_proposal.AccountBudgetProposal
    account_link: gagr_account_link.AccountLink
    ad: gagr_ad.Ad
    ad_group: gagr_ad_group.AdGroup
    ad_group_ad: gagr_ad_group_ad.AdGroupAd
    ad_group_ad_asset_combination_view: gagr_ad_group_ad_asset_combination_view.AdGroupAdAssetCombinationView
    ad_group_ad_asset_view: gagr_ad_group_ad_asset_view.AdGroupAdAssetView
    ad_group_ad_label: gagr_ad_group_ad_label.AdGroupAdLabel
    ad_group_asset: gagr_ad_group_asset.AdGroupAsset
    ad_group_asset_set: gagr_ad_group_asset_set.AdGroupAssetSet
    ad_group_audience_view: gagr_ad_group_audience_view.AdGroupAudienceView
    ad_group_bid_modifier: gagr_ad_group_bid_modifier.AdGroupBidModifier
    ad_group_criterion: gagr_ad_group_criterion.AdGroupCriterion
    ad_group_criterion_customizer: gagr_ad_group_criterion_customizer.AdGroupCriterionCustomizer
    ad_group_criterion_label: gagr_ad_group_criterion_label.AdGroupCriterionLabel
    ad_group_criterion_simulation: gagr_ad_group_criterion_simulation.AdGroupCriterionSimulation
    ad_group_customizer: gagr_ad_group_customizer.AdGroupCustomizer
    ad_group_extension_setting: gagr_ad_group_extension_setting.AdGroupExtensionSetting
    ad_group_feed: gagr_ad_group_feed.AdGroupFeed
    ad_group_label: gagr_ad_group_label.AdGroupLabel
    ad_group_simulation: gagr_ad_group_simulation.AdGroupSimulation
    ad_parameter: gagr_ad_parameter.AdParameter
    age_range_view: gagr_age_range_view.AgeRangeView
    ad_schedule_view: gagr_ad_schedule_view.AdScheduleView
    domain_category: gagr_domain_category.DomainCategory
    asset: gagr_asset.Asset
    asset_field_type_view: gagr_asset_field_type_view.AssetFieldTypeView
    channel_aggregate_asset_view: gagr_channel_aggregate_asset_view.ChannelAggregateAssetView
    campaign_aggregate_asset_view: gagr_campaign_aggregate_asset_view.CampaignAggregateAssetView
    asset_group_asset: gagr_asset_group_asset.AssetGroupAsset
    asset_group_signal: gagr_asset_group_signal.AssetGroupSignal
    asset_group_listing_group_filter: gagr_asset_group_listing_group_filter.AssetGroupListingGroupFilter
    asset_group_product_group_view: gagr_asset_group_product_group_view.AssetGroupProductGroupView
    asset_group_top_combination_view: gagr_asset_group_top_combination_view.AssetGroupTopCombinationView
    asset_group: gagr_asset_group.AssetGroup
    asset_set_asset: gagr_asset_set_asset.AssetSetAsset
    asset_set: gagr_asset_set.AssetSet
    asset_set_type_view: gagr_asset_set_type_view.AssetSetTypeView
    batch_job: gagr_batch_job.BatchJob
    bidding_data_exclusion: gagr_bidding_data_exclusion.BiddingDataExclusion
    bidding_seasonality_adjustment: gagr_bidding_seasonality_adjustment.BiddingSeasonalityAdjustment
    bidding_strategy: gagr_bidding_strategy.BiddingStrategy
    bidding_strategy_simulation: gagr_bidding_strategy_simulation.BiddingStrategySimulation
    billing_setup: gagr_billing_setup.BillingSetup
    call_view: gagr_call_view.CallView
    campaign_budget: gagr_campaign_budget.CampaignBudget
    campaign: gagr_campaign.Campaign
    campaign_asset: gagr_campaign_asset.CampaignAsset
    campaign_asset_set: gagr_campaign_asset_set.CampaignAssetSet
    campaign_audience_view: gagr_campaign_audience_view.CampaignAudienceView
    campaign_bid_modifier: gagr_campaign_bid_modifier.CampaignBidModifier
    campaign_conversion_goal: gagr_campaign_conversion_goal.CampaignConversionGoal
    campaign_criterion: gagr_campaign_criterion.CampaignCriterion
    campaign_customizer: gagr_campaign_customizer.CampaignCustomizer
    campaign_draft: gagr_campaign_draft.CampaignDraft
    campaign_extension_setting: gagr_campaign_extension_setting.CampaignExtensionSetting
    campaign_feed: gagr_campaign_feed.CampaignFeed
    campaign_group: gagr_campaign_group.CampaignGroup
    campaign_label: gagr_campaign_label.CampaignLabel
    campaign_lifecycle_goal: gagr_campaign_lifecycle_goal.CampaignLifecycleGoal
    campaign_search_term_insight: gagr_campaign_search_term_insight.CampaignSearchTermInsight
    campaign_shared_set: gagr_campaign_shared_set.CampaignSharedSet
    campaign_simulation: gagr_campaign_simulation.CampaignSimulation
    carrier_constant: gagr_carrier_constant.CarrierConstant
    change_event: gagr_change_event.ChangeEvent
    change_status: gagr_change_status.ChangeStatus
    combined_audience: gagr_combined_audience.CombinedAudience
    audience: gagr_audience.Audience
    conversion_action: gagr_conversion_action.ConversionAction
    conversion_custom_variable: gagr_conversion_custom_variable.ConversionCustomVariable
    conversion_goal_campaign_config: gagr_conversion_goal_campaign_config.ConversionGoalCampaignConfig
    conversion_value_rule: gagr_conversion_value_rule.ConversionValueRule
    conversion_value_rule_set: gagr_conversion_value_rule_set.ConversionValueRuleSet
    click_view: gagr_click_view.ClickView
    currency_constant: gagr_currency_constant.CurrencyConstant
    custom_audience: gagr_custom_audience.CustomAudience
    custom_conversion_goal: gagr_custom_conversion_goal.CustomConversionGoal
    custom_interest: gagr_custom_interest.CustomInterest
    customer: gagr_customer.Customer
    customer_asset: gagr_customer_asset.CustomerAsset
    customer_asset_set: gagr_customer_asset_set.CustomerAssetSet
    accessible_bidding_strategy: gagr_accessible_bidding_strategy.AccessibleBiddingStrategy
    customer_customizer: gagr_customer_customizer.CustomerCustomizer
    customer_manager_link: gagr_customer_manager_link.CustomerManagerLink
    customer_client_link: gagr_customer_client_link.CustomerClientLink
    customer_client: gagr_customer_client.CustomerClient
    customer_conversion_goal: gagr_customer_conversion_goal.CustomerConversionGoal
    customer_extension_setting: gagr_customer_extension_setting.CustomerExtensionSetting
    customer_feed: gagr_customer_feed.CustomerFeed
    customer_label: gagr_customer_label.CustomerLabel
    customer_lifecycle_goal: gagr_customer_lifecycle_goal.CustomerLifecycleGoal
    customer_negative_criterion: gagr_customer_negative_criterion.CustomerNegativeCriterion
    customer_search_term_insight: gagr_customer_search_term_insight.CustomerSearchTermInsight
    customer_user_access: gagr_customer_user_access.CustomerUserAccess
    customer_user_access_invitation: gagr_customer_user_access_invitation.CustomerUserAccessInvitation
    customizer_attribute: gagr_customizer_attribute.CustomizerAttribute
    data_link: gagr_data_link.DataLink
    detail_placement_view: gagr_detail_placement_view.DetailPlacementView
    detailed_demographic: gagr_detailed_demographic.DetailedDemographic
    display_keyword_view: gagr_display_keyword_view.DisplayKeywordView
    distance_view: gagr_distance_view.DistanceView
    dynamic_search_ads_search_term_view: gagr_dynamic_search_ads_search_term_view.DynamicSearchAdsSearchTermView
    expanded_landing_page_view: gagr_expanded_landing_page_view.ExpandedLandingPageView
    extension_feed_item: gagr_extension_feed_item.ExtensionFeedItem
    feed: gagr_feed.Feed
    feed_item: gagr_feed_item.FeedItem
    feed_item_set: gagr_feed_item_set.FeedItemSet
    feed_item_set_link: gagr_feed_item_set_link.FeedItemSetLink
    feed_item_target: gagr_feed_item_target.FeedItemTarget
    feed_mapping: gagr_feed_mapping.FeedMapping
    feed_placeholder_view: gagr_feed_placeholder_view.FeedPlaceholderView
    gender_view: gagr_gender_view.GenderView
    geo_target_constant: gagr_geo_target_constant.GeoTargetConstant
    geographic_view: gagr_geographic_view.GeographicView
    group_placement_view: gagr_group_placement_view.GroupPlacementView
    hotel_group_view: gagr_hotel_group_view.HotelGroupView
    hotel_performance_view: gagr_hotel_performance_view.HotelPerformanceView
    hotel_reconciliation: gagr_hotel_reconciliation.HotelReconciliation
    income_range_view: gagr_income_range_view.IncomeRangeView
    keyword_view: gagr_keyword_view.KeywordView
    keyword_plan: gagr_keyword_plan.KeywordPlan
    keyword_plan_campaign: gagr_keyword_plan_campaign.KeywordPlanCampaign
    keyword_plan_campaign_keyword: gagr_keyword_plan_campaign_keyword.KeywordPlanCampaignKeyword
    keyword_plan_ad_group: gagr_keyword_plan_ad_group.KeywordPlanAdGroup
    keyword_plan_ad_group_keyword: gagr_keyword_plan_ad_group_keyword.KeywordPlanAdGroupKeyword
    keyword_theme_constant: gagr_keyword_theme_constant.KeywordThemeConstant
    label: gagr_label.Label
    landing_page_view: gagr_landing_page_view.LandingPageView
    language_constant: gagr_language_constant.LanguageConstant
    location_view: gagr_location_view.LocationView
    managed_placement_view: gagr_managed_placement_view.ManagedPlacementView
    content_criterion_view: gagr_content_criterion_view.ContentCriterionView
    media_file: gagr_media_file.MediaFile
    local_services_employee: gagr_local_services_employee.LocalServicesEmployee
    local_services_verification_artifact: gagr_local_services_verification_artifact.LocalServicesVerificationArtifact
    mobile_app_category_constant: gagr_mobile_app_category_constant.MobileAppCategoryConstant
    mobile_device_constant: gagr_mobile_device_constant.MobileDeviceConstant
    offline_conversion_upload_client_summary: gagr_offline_conversion_upload_client_summary.OfflineConversionUploadClientSummary
    offline_conversion_upload_conversion_action_summary: gagr_offline_conversion_upload_conversion_action_summary.OfflineConversionUploadConversionActionSummary
    offline_user_data_job: gagr_offline_user_data_job.OfflineUserDataJob
    operating_system_version_constant: gagr_operating_system_version_constant.OperatingSystemVersionConstant
    paid_organic_search_term_view: gagr_paid_organic_search_term_view.PaidOrganicSearchTermView
    qualifying_question: gagr_qualifying_question.QualifyingQuestion
    parental_status_view: gagr_parental_status_view.ParentalStatusView
    per_store_view: gagr_per_store_view.PerStoreView
    performance_max_placement_view: gagr_performance_max_placement_view.PerformanceMaxPlacementView
    product_category_constant: gagr_product_category_constant.ProductCategoryConstant
    product_group_view: gagr_product_group_view.ProductGroupView
    product_link: gagr_product_link.ProductLink
    product_link_invitation: gagr_product_link_invitation.ProductLinkInvitation
    recommendation: gagr_recommendation.Recommendation
    recommendation_subscription: gagr_recommendation_subscription.RecommendationSubscription
    search_term_view: gagr_search_term_view.SearchTermView
    shared_criterion: gagr_shared_criterion.SharedCriterion
    shared_set: gagr_shared_set.SharedSet
    smart_campaign_setting: gagr_smart_campaign_setting.SmartCampaignSetting
    shopping_performance_view: gagr_shopping_performance_view.ShoppingPerformanceView
    shopping_product: gagr_shopping_product.ShoppingProduct
    smart_campaign_search_term_view: gagr_smart_campaign_search_term_view.SmartCampaignSearchTermView
    third_party_app_analytics_link: gagr_third_party_app_analytics_link.ThirdPartyAppAnalyticsLink
    topic_view: gagr_topic_view.TopicView
    travel_activity_group_view: gagr_travel_activity_group_view.TravelActivityGroupView
    travel_activity_performance_view: gagr_travel_activity_performance_view.TravelActivityPerformanceView
    experiment: gagr_experiment.Experiment
    experiment_arm: gagr_experiment_arm.ExperimentArm
    user_interest: gagr_user_interest.UserInterest
    life_event: gagr_life_event.LifeEvent
    user_list: gagr_user_list.UserList
    user_list_customer_type: gagr_user_list_customer_type.UserListCustomerType
    user_location_view: gagr_user_location_view.UserLocationView
    remarketing_action: gagr_remarketing_action.RemarketingAction
    topic_constant: gagr_topic_constant.TopicConstant
    video: gagr_video.Video
    webpage_view: gagr_webpage_view.WebpageView
    lead_form_submission_data: gagr_lead_form_submission_data.LeadFormSubmissionData
    local_services_lead: gagr_local_services_lead.LocalServicesLead
    local_services_lead_conversation: gagr_local_services_lead_conversation.LocalServicesLeadConversation
    android_privacy_shared_key_google_ad_group: gagr_android_privacy_shared_key_google_ad_group.AndroidPrivacySharedKeyGoogleAdGroup
    android_privacy_shared_key_google_campaign: gagr_android_privacy_shared_key_google_campaign.AndroidPrivacySharedKeyGoogleCampaign
    android_privacy_shared_key_google_network_type: gagr_android_privacy_shared_key_google_network_type.AndroidPrivacySharedKeyGoogleNetworkType
    metrics: gagc_metrics.Metrics
    segments: gagc_segments.Segments

class MutateGoogleAdsRequest(proto.Message):
    customer_id: str
    mutate_operations: MutableSequence['MutateOperation']
    partial_failure: bool
    validate_only: bool
    response_content_type: gage_response_content_type.ResponseContentTypeEnum.ResponseContentType

class MutateGoogleAdsResponse(proto.Message):
    partial_failure_error: status_pb2.Status
    mutate_operation_responses: MutableSequence['MutateOperationResponse']

class MutateOperation(proto.Message):
    ad_group_ad_label_operation: ad_group_ad_label_service.AdGroupAdLabelOperation
    ad_group_ad_operation: ad_group_ad_service.AdGroupAdOperation
    ad_group_asset_operation: ad_group_asset_service.AdGroupAssetOperation
    ad_group_bid_modifier_operation: ad_group_bid_modifier_service.AdGroupBidModifierOperation
    ad_group_criterion_customizer_operation: ad_group_criterion_customizer_service.AdGroupCriterionCustomizerOperation
    ad_group_criterion_label_operation: ad_group_criterion_label_service.AdGroupCriterionLabelOperation
    ad_group_criterion_operation: ad_group_criterion_service.AdGroupCriterionOperation
    ad_group_customizer_operation: ad_group_customizer_service.AdGroupCustomizerOperation
    ad_group_extension_setting_operation: ad_group_extension_setting_service.AdGroupExtensionSettingOperation
    ad_group_feed_operation: ad_group_feed_service.AdGroupFeedOperation
    ad_group_label_operation: ad_group_label_service.AdGroupLabelOperation
    ad_group_operation: ad_group_service.AdGroupOperation
    ad_operation: ad_service.AdOperation
    ad_parameter_operation: ad_parameter_service.AdParameterOperation
    asset_operation: asset_service.AssetOperation
    asset_group_asset_operation: asset_group_asset_service.AssetGroupAssetOperation
    asset_group_listing_group_filter_operation: asset_group_listing_group_filter_service.AssetGroupListingGroupFilterOperation
    asset_group_signal_operation: asset_group_signal_service.AssetGroupSignalOperation
    asset_group_operation: asset_group_service.AssetGroupOperation
    asset_set_asset_operation: asset_set_asset_service.AssetSetAssetOperation
    asset_set_operation: asset_set_service.AssetSetOperation
    audience_operation: audience_service.AudienceOperation
    bidding_data_exclusion_operation: bidding_data_exclusion_service.BiddingDataExclusionOperation
    bidding_seasonality_adjustment_operation: bidding_seasonality_adjustment_service.BiddingSeasonalityAdjustmentOperation
    bidding_strategy_operation: bidding_strategy_service.BiddingStrategyOperation
    campaign_asset_operation: campaign_asset_service.CampaignAssetOperation
    campaign_asset_set_operation: campaign_asset_set_service.CampaignAssetSetOperation
    campaign_bid_modifier_operation: campaign_bid_modifier_service.CampaignBidModifierOperation
    campaign_budget_operation: campaign_budget_service.CampaignBudgetOperation
    campaign_conversion_goal_operation: campaign_conversion_goal_service.CampaignConversionGoalOperation
    campaign_criterion_operation: campaign_criterion_service.CampaignCriterionOperation
    campaign_customizer_operation: campaign_customizer_service.CampaignCustomizerOperation
    campaign_draft_operation: campaign_draft_service.CampaignDraftOperation
    campaign_extension_setting_operation: campaign_extension_setting_service.CampaignExtensionSettingOperation
    campaign_feed_operation: campaign_feed_service.CampaignFeedOperation
    campaign_group_operation: campaign_group_service.CampaignGroupOperation
    campaign_label_operation: campaign_label_service.CampaignLabelOperation
    campaign_operation: campaign_service.CampaignOperation
    campaign_shared_set_operation: campaign_shared_set_service.CampaignSharedSetOperation
    conversion_action_operation: conversion_action_service.ConversionActionOperation
    conversion_custom_variable_operation: conversion_custom_variable_service.ConversionCustomVariableOperation
    conversion_goal_campaign_config_operation: conversion_goal_campaign_config_service.ConversionGoalCampaignConfigOperation
    conversion_value_rule_operation: conversion_value_rule_service.ConversionValueRuleOperation
    conversion_value_rule_set_operation: conversion_value_rule_set_service.ConversionValueRuleSetOperation
    custom_conversion_goal_operation: custom_conversion_goal_service.CustomConversionGoalOperation
    customer_asset_operation: customer_asset_service.CustomerAssetOperation
    customer_conversion_goal_operation: customer_conversion_goal_service.CustomerConversionGoalOperation
    customer_customizer_operation: customer_customizer_service.CustomerCustomizerOperation
    customer_extension_setting_operation: customer_extension_setting_service.CustomerExtensionSettingOperation
    customer_feed_operation: customer_feed_service.CustomerFeedOperation
    customer_label_operation: customer_label_service.CustomerLabelOperation
    customer_negative_criterion_operation: customer_negative_criterion_service.CustomerNegativeCriterionOperation
    customer_operation: customer_service.CustomerOperation
    customizer_attribute_operation: customizer_attribute_service.CustomizerAttributeOperation
    experiment_operation: experiment_service.ExperimentOperation
    experiment_arm_operation: experiment_arm_service.ExperimentArmOperation
    extension_feed_item_operation: extension_feed_item_service.ExtensionFeedItemOperation
    feed_item_operation: feed_item_service.FeedItemOperation
    feed_item_set_operation: feed_item_set_service.FeedItemSetOperation
    feed_item_set_link_operation: feed_item_set_link_service.FeedItemSetLinkOperation
    feed_item_target_operation: feed_item_target_service.FeedItemTargetOperation
    feed_mapping_operation: feed_mapping_service.FeedMappingOperation
    feed_operation: feed_service.FeedOperation
    keyword_plan_ad_group_operation: keyword_plan_ad_group_service.KeywordPlanAdGroupOperation
    keyword_plan_ad_group_keyword_operation: keyword_plan_ad_group_keyword_service.KeywordPlanAdGroupKeywordOperation
    keyword_plan_campaign_keyword_operation: keyword_plan_campaign_keyword_service.KeywordPlanCampaignKeywordOperation
    keyword_plan_campaign_operation: keyword_plan_campaign_service.KeywordPlanCampaignOperation
    keyword_plan_operation: keyword_plan_service.KeywordPlanOperation
    label_operation: label_service.LabelOperation
    recommendation_subscription_operation: recommendation_subscription_service.RecommendationSubscriptionOperation
    remarketing_action_operation: remarketing_action_service.RemarketingActionOperation
    shared_criterion_operation: shared_criterion_service.SharedCriterionOperation
    shared_set_operation: shared_set_service.SharedSetOperation
    smart_campaign_setting_operation: smart_campaign_setting_service.SmartCampaignSettingOperation
    user_list_operation: user_list_service.UserListOperation

class MutateOperationResponse(proto.Message):
    ad_group_ad_label_result: ad_group_ad_label_service.MutateAdGroupAdLabelResult
    ad_group_ad_result: ad_group_ad_service.MutateAdGroupAdResult
    ad_group_asset_result: ad_group_asset_service.MutateAdGroupAssetResult
    ad_group_bid_modifier_result: ad_group_bid_modifier_service.MutateAdGroupBidModifierResult
    ad_group_criterion_customizer_result: ad_group_criterion_customizer_service.MutateAdGroupCriterionCustomizerResult
    ad_group_criterion_label_result: ad_group_criterion_label_service.MutateAdGroupCriterionLabelResult
    ad_group_criterion_result: ad_group_criterion_service.MutateAdGroupCriterionResult
    ad_group_customizer_result: ad_group_customizer_service.MutateAdGroupCustomizerResult
    ad_group_extension_setting_result: ad_group_extension_setting_service.MutateAdGroupExtensionSettingResult
    ad_group_feed_result: ad_group_feed_service.MutateAdGroupFeedResult
    ad_group_label_result: ad_group_label_service.MutateAdGroupLabelResult
    ad_group_result: ad_group_service.MutateAdGroupResult
    ad_parameter_result: ad_parameter_service.MutateAdParameterResult
    ad_result: ad_service.MutateAdResult
    asset_result: asset_service.MutateAssetResult
    asset_group_asset_result: asset_group_asset_service.MutateAssetGroupAssetResult
    asset_group_listing_group_filter_result: asset_group_listing_group_filter_service.MutateAssetGroupListingGroupFilterResult
    asset_group_signal_result: asset_group_signal_service.MutateAssetGroupSignalResult
    asset_group_result: asset_group_service.MutateAssetGroupResult
    asset_set_asset_result: asset_set_asset_service.MutateAssetSetAssetResult
    asset_set_result: asset_set_service.MutateAssetSetResult
    audience_result: audience_service.MutateAudienceResult
    bidding_data_exclusion_result: bidding_data_exclusion_service.MutateBiddingDataExclusionsResult
    bidding_seasonality_adjustment_result: bidding_seasonality_adjustment_service.MutateBiddingSeasonalityAdjustmentsResult
    bidding_strategy_result: bidding_strategy_service.MutateBiddingStrategyResult
    campaign_asset_result: campaign_asset_service.MutateCampaignAssetResult
    campaign_asset_set_result: campaign_asset_set_service.MutateCampaignAssetSetResult
    campaign_bid_modifier_result: campaign_bid_modifier_service.MutateCampaignBidModifierResult
    campaign_budget_result: campaign_budget_service.MutateCampaignBudgetResult
    campaign_conversion_goal_result: campaign_conversion_goal_service.MutateCampaignConversionGoalResult
    campaign_criterion_result: campaign_criterion_service.MutateCampaignCriterionResult
    campaign_customizer_result: campaign_customizer_service.MutateCampaignCustomizerResult
    campaign_draft_result: campaign_draft_service.MutateCampaignDraftResult
    campaign_extension_setting_result: campaign_extension_setting_service.MutateCampaignExtensionSettingResult
    campaign_feed_result: campaign_feed_service.MutateCampaignFeedResult
    campaign_group_result: campaign_group_service.MutateCampaignGroupResult
    campaign_label_result: campaign_label_service.MutateCampaignLabelResult
    campaign_result: campaign_service.MutateCampaignResult
    campaign_shared_set_result: campaign_shared_set_service.MutateCampaignSharedSetResult
    conversion_action_result: conversion_action_service.MutateConversionActionResult
    conversion_custom_variable_result: conversion_custom_variable_service.MutateConversionCustomVariableResult
    conversion_goal_campaign_config_result: conversion_goal_campaign_config_service.MutateConversionGoalCampaignConfigResult
    conversion_value_rule_result: conversion_value_rule_service.MutateConversionValueRuleResult
    conversion_value_rule_set_result: conversion_value_rule_set_service.MutateConversionValueRuleSetResult
    custom_conversion_goal_result: custom_conversion_goal_service.MutateCustomConversionGoalResult
    customer_asset_result: customer_asset_service.MutateCustomerAssetResult
    customer_conversion_goal_result: customer_conversion_goal_service.MutateCustomerConversionGoalResult
    customer_customizer_result: customer_customizer_service.MutateCustomerCustomizerResult
    customer_extension_setting_result: customer_extension_setting_service.MutateCustomerExtensionSettingResult
    customer_feed_result: customer_feed_service.MutateCustomerFeedResult
    customer_label_result: customer_label_service.MutateCustomerLabelResult
    customer_negative_criterion_result: customer_negative_criterion_service.MutateCustomerNegativeCriteriaResult
    customer_result: customer_service.MutateCustomerResult
    customizer_attribute_result: customizer_attribute_service.MutateCustomizerAttributeResult
    experiment_result: experiment_service.MutateExperimentResult
    experiment_arm_result: experiment_arm_service.MutateExperimentArmResult
    extension_feed_item_result: extension_feed_item_service.MutateExtensionFeedItemResult
    feed_item_result: feed_item_service.MutateFeedItemResult
    feed_item_set_result: feed_item_set_service.MutateFeedItemSetResult
    feed_item_set_link_result: feed_item_set_link_service.MutateFeedItemSetLinkResult
    feed_item_target_result: feed_item_target_service.MutateFeedItemTargetResult
    feed_mapping_result: feed_mapping_service.MutateFeedMappingResult
    feed_result: feed_service.MutateFeedResult
    keyword_plan_ad_group_result: keyword_plan_ad_group_service.MutateKeywordPlanAdGroupResult
    keyword_plan_campaign_result: keyword_plan_campaign_service.MutateKeywordPlanCampaignResult
    keyword_plan_ad_group_keyword_result: keyword_plan_ad_group_keyword_service.MutateKeywordPlanAdGroupKeywordResult
    keyword_plan_campaign_keyword_result: keyword_plan_campaign_keyword_service.MutateKeywordPlanCampaignKeywordResult
    keyword_plan_result: keyword_plan_service.MutateKeywordPlansResult
    label_result: label_service.MutateLabelResult
    recommendation_subscription_result: recommendation_subscription_service.MutateRecommendationSubscriptionResult
    remarketing_action_result: remarketing_action_service.MutateRemarketingActionResult
    shared_criterion_result: shared_criterion_service.MutateSharedCriterionResult
    shared_set_result: shared_set_service.MutateSharedSetResult
    smart_campaign_setting_result: smart_campaign_setting_service.MutateSmartCampaignSettingResult
    user_list_result: user_list_service.MutateUserListResult

class SearchSettings(proto.Message):
    omit_results: bool
    return_summary_row: bool
    return_total_results_count: bool
