from .types.ad_asset import (
    AdAppDeepLinkAsset as AdAppDeepLinkAsset,
    AdCallToActionAsset as AdCallToActionAsset,
    AdDemandGenCarouselCardAsset as AdDemandGenCarouselCardAsset,
    AdImageAsset as AdImageAsset,
    AdMediaBundleAsset as AdMediaBundleAsset,
    AdTextAsset as AdTextAsset,
    AdVideoAsset as AdVideoAsset,
    AdVideoAssetInfo as AdVideoAssetInfo,
    AdVideoAssetInventoryPreferences as AdVideoAssetInventoryPreferences,
)
from .types.ad_type_infos import (
    AppAdInfo as AppAdInfo,
    AppEngagementAdInfo as AppEngagementAdInfo,
    AppPreRegistrationAdInfo as AppPreRegistrationAdInfo,
    CallAdInfo as CallAdInfo,
    DemandGenCarouselAdInfo as DemandGenCarouselAdInfo,
    DemandGenMultiAssetAdInfo as DemandGenMultiAssetAdInfo,
    DemandGenProductAdInfo as DemandGenProductAdInfo,
    DemandGenVideoResponsiveAdInfo as DemandGenVideoResponsiveAdInfo,
    DisplayUploadAdInfo as DisplayUploadAdInfo,
    ExpandedDynamicSearchAdInfo as ExpandedDynamicSearchAdInfo,
    ExpandedTextAdInfo as ExpandedTextAdInfo,
    HotelAdInfo as HotelAdInfo,
    ImageAdInfo as ImageAdInfo,
    InFeedVideoAdInfo as InFeedVideoAdInfo,
    LegacyAppInstallAdInfo as LegacyAppInstallAdInfo,
    LegacyResponsiveDisplayAdInfo as LegacyResponsiveDisplayAdInfo,
    LocalAdInfo as LocalAdInfo,
    ResponsiveDisplayAdControlSpec as ResponsiveDisplayAdControlSpec,
    ResponsiveDisplayAdInfo as ResponsiveDisplayAdInfo,
    ResponsiveSearchAdInfo as ResponsiveSearchAdInfo,
    ShoppingComparisonListingAdInfo as ShoppingComparisonListingAdInfo,
    ShoppingProductAdInfo as ShoppingProductAdInfo,
    ShoppingSmartAdInfo as ShoppingSmartAdInfo,
    SmartCampaignAdInfo as SmartCampaignAdInfo,
    TextAdInfo as TextAdInfo,
    TravelAdInfo as TravelAdInfo,
    VideoAdInfo as VideoAdInfo,
    VideoBumperInStreamAdInfo as VideoBumperInStreamAdInfo,
    VideoNonSkippableInStreamAdInfo as VideoNonSkippableInStreamAdInfo,
    VideoOutstreamAdInfo as VideoOutstreamAdInfo,
    VideoResponsiveAdInfo as VideoResponsiveAdInfo,
    VideoTrueViewInStreamAdInfo as VideoTrueViewInStreamAdInfo,
)
from .types.asset_policy import (
    AdAssetPolicySummary as AdAssetPolicySummary,
    AssetDisapproved as AssetDisapproved,
    AssetLinkPrimaryStatusDetails as AssetLinkPrimaryStatusDetails,
)
from .types.asset_set_types import (
    BusinessProfileBusinessNameFilter as BusinessProfileBusinessNameFilter,
    BusinessProfileLocationGroup as BusinessProfileLocationGroup,
    BusinessProfileLocationSet as BusinessProfileLocationSet,
    ChainFilter as ChainFilter,
    ChainLocationGroup as ChainLocationGroup,
    ChainSet as ChainSet,
    DynamicBusinessProfileLocationGroupFilter as DynamicBusinessProfileLocationGroupFilter,
    LocationSet as LocationSet,
    MapsLocationInfo as MapsLocationInfo,
    MapsLocationSet as MapsLocationSet,
)
from .types.asset_types import (
    AppDeepLinkAsset as AppDeepLinkAsset,
    BookOnGoogleAsset as BookOnGoogleAsset,
    BusinessMessageAsset as BusinessMessageAsset,
    BusinessMessageCallToActionInfo as BusinessMessageCallToActionInfo,
    BusinessProfileLocation as BusinessProfileLocation,
    CallAsset as CallAsset,
    CalloutAsset as CalloutAsset,
    CallToActionAsset as CallToActionAsset,
    DemandGenCarouselCardAsset as DemandGenCarouselCardAsset,
    DynamicCustomAsset as DynamicCustomAsset,
    DynamicEducationAsset as DynamicEducationAsset,
    DynamicFlightsAsset as DynamicFlightsAsset,
    DynamicHotelsAndRentalsAsset as DynamicHotelsAndRentalsAsset,
    DynamicJobsAsset as DynamicJobsAsset,
    DynamicLocalAsset as DynamicLocalAsset,
    DynamicRealEstateAsset as DynamicRealEstateAsset,
    DynamicTravelAsset as DynamicTravelAsset,
    HotelCalloutAsset as HotelCalloutAsset,
    HotelPropertyAsset as HotelPropertyAsset,
    ImageAsset as ImageAsset,
    ImageDimension as ImageDimension,
    LeadFormAsset as LeadFormAsset,
    LeadFormCustomQuestionField as LeadFormCustomQuestionField,
    LeadFormDeliveryMethod as LeadFormDeliveryMethod,
    LeadFormField as LeadFormField,
    LeadFormSingleChoiceAnswers as LeadFormSingleChoiceAnswers,
    LocationAsset as LocationAsset,
    MediaBundleAsset as MediaBundleAsset,
    MobileAppAsset as MobileAppAsset,
    PageFeedAsset as PageFeedAsset,
    PriceAsset as PriceAsset,
    PriceOffering as PriceOffering,
    PromotionAsset as PromotionAsset,
    SitelinkAsset as SitelinkAsset,
    StructuredSnippetAsset as StructuredSnippetAsset,
    TextAsset as TextAsset,
    WebhookDelivery as WebhookDelivery,
    WhatsappBusinessMessageInfo as WhatsappBusinessMessageInfo,
    YoutubeVideoAsset as YoutubeVideoAsset,
)
from .types.asset_usage import AssetUsage as AssetUsage
from .types.audience_insights_attribute import (
    AudienceInsightsAttribute as AudienceInsightsAttribute,
    AudienceInsightsAttributeMetadata as AudienceInsightsAttributeMetadata,
    AudienceInsightsCategory as AudienceInsightsCategory,
    AudienceInsightsDynamicLineup as AudienceInsightsDynamicLineup,
    AudienceInsightsEntity as AudienceInsightsEntity,
    AudienceInsightsTopic as AudienceInsightsTopic,
    DynamicLineupAttributeMetadata as DynamicLineupAttributeMetadata,
    KnowledgeGraphAttributeMetadata as KnowledgeGraphAttributeMetadata,
    LocationAttributeMetadata as LocationAttributeMetadata,
    UserInterestAttributeMetadata as UserInterestAttributeMetadata,
    YouTubeChannelAttributeMetadata as YouTubeChannelAttributeMetadata,
    YouTubeVideoAttributeMetadata as YouTubeVideoAttributeMetadata,
)
from .types.audiences import (
    AgeDimension as AgeDimension,
    AgeSegment as AgeSegment,
    AudienceDimension as AudienceDimension,
    AudienceExclusionDimension as AudienceExclusionDimension,
    AudienceSegment as AudienceSegment,
    AudienceSegmentDimension as AudienceSegmentDimension,
    CustomAudienceSegment as CustomAudienceSegment,
    DetailedDemographicSegment as DetailedDemographicSegment,
    ExclusionSegment as ExclusionSegment,
    GenderDimension as GenderDimension,
    HouseholdIncomeDimension as HouseholdIncomeDimension,
    LifeEventSegment as LifeEventSegment,
    ParentalStatusDimension as ParentalStatusDimension,
    UserInterestSegment as UserInterestSegment,
    UserListSegment as UserListSegment,
)
from .types.bidding import (
    Commission as Commission,
    EnhancedCpc as EnhancedCpc,
    FixedCpm as FixedCpm,
    FixedCpmTargetFrequencyGoalInfo as FixedCpmTargetFrequencyGoalInfo,
    ManualCpa as ManualCpa,
    ManualCpc as ManualCpc,
    ManualCpm as ManualCpm,
    ManualCpv as ManualCpv,
    MaximizeConversions as MaximizeConversions,
    MaximizeConversionValue as MaximizeConversionValue,
    PercentCpc as PercentCpc,
    TargetCpa as TargetCpa,
    TargetCpm as TargetCpm,
    TargetCpmTargetFrequencyGoal as TargetCpmTargetFrequencyGoal,
    TargetCpv as TargetCpv,
    TargetImpressionShare as TargetImpressionShare,
    TargetRoas as TargetRoas,
    TargetSpend as TargetSpend,
)
from .types.click_location import ClickLocation as ClickLocation
from .types.consent import Consent as Consent
from .types.criteria import (
    ActivityCityInfo as ActivityCityInfo,
    ActivityCountryInfo as ActivityCountryInfo,
    ActivityIdInfo as ActivityIdInfo,
    ActivityRatingInfo as ActivityRatingInfo,
    ActivityStateInfo as ActivityStateInfo,
    AddressInfo as AddressInfo,
    AdScheduleInfo as AdScheduleInfo,
    AgeRangeInfo as AgeRangeInfo,
    AppPaymentModelInfo as AppPaymentModelInfo,
    AudienceInfo as AudienceInfo,
    BrandInfo as BrandInfo,
    BrandListInfo as BrandListInfo,
    CarrierInfo as CarrierInfo,
    CombinedAudienceInfo as CombinedAudienceInfo,
    ContentLabelInfo as ContentLabelInfo,
    CustomAffinityInfo as CustomAffinityInfo,
    CustomAudienceInfo as CustomAudienceInfo,
    CustomIntentInfo as CustomIntentInfo,
    DeviceInfo as DeviceInfo,
    GenderInfo as GenderInfo,
    GeoPointInfo as GeoPointInfo,
    HotelAdvanceBookingWindowInfo as HotelAdvanceBookingWindowInfo,
    HotelCheckInDateRangeInfo as HotelCheckInDateRangeInfo,
    HotelCheckInDayInfo as HotelCheckInDayInfo,
    HotelCityInfo as HotelCityInfo,
    HotelClassInfo as HotelClassInfo,
    HotelCountryRegionInfo as HotelCountryRegionInfo,
    HotelDateSelectionTypeInfo as HotelDateSelectionTypeInfo,
    HotelIdInfo as HotelIdInfo,
    HotelLengthOfStayInfo as HotelLengthOfStayInfo,
    HotelStateInfo as HotelStateInfo,
    IncomeRangeInfo as IncomeRangeInfo,
    InteractionTypeInfo as InteractionTypeInfo,
    IpBlockInfo as IpBlockInfo,
    KeywordInfo as KeywordInfo,
    KeywordThemeInfo as KeywordThemeInfo,
    LanguageInfo as LanguageInfo,
    ListingDimensionInfo as ListingDimensionInfo,
    ListingDimensionPath as ListingDimensionPath,
    ListingGroupInfo as ListingGroupInfo,
    ListingScopeInfo as ListingScopeInfo,
    LocalServiceIdInfo as LocalServiceIdInfo,
    LocationGroupInfo as LocationGroupInfo,
    LocationInfo as LocationInfo,
    MobileAppCategoryInfo as MobileAppCategoryInfo,
    MobileApplicationInfo as MobileApplicationInfo,
    MobileDeviceInfo as MobileDeviceInfo,
    NegativeKeywordListInfo as NegativeKeywordListInfo,
    OperatingSystemVersionInfo as OperatingSystemVersionInfo,
    ParentalStatusInfo as ParentalStatusInfo,
    PlacementInfo as PlacementInfo,
    ProductBrandInfo as ProductBrandInfo,
    ProductCategoryInfo as ProductCategoryInfo,
    ProductChannelExclusivityInfo as ProductChannelExclusivityInfo,
    ProductChannelInfo as ProductChannelInfo,
    ProductConditionInfo as ProductConditionInfo,
    ProductCustomAttributeInfo as ProductCustomAttributeInfo,
    ProductGroupingInfo as ProductGroupingInfo,
    ProductItemIdInfo as ProductItemIdInfo,
    ProductLabelsInfo as ProductLabelsInfo,
    ProductLegacyConditionInfo as ProductLegacyConditionInfo,
    ProductTypeFullInfo as ProductTypeFullInfo,
    ProductTypeInfo as ProductTypeInfo,
    ProximityInfo as ProximityInfo,
    SearchThemeInfo as SearchThemeInfo,
    TopicInfo as TopicInfo,
    UnknownListingDimensionInfo as UnknownListingDimensionInfo,
    UserInterestInfo as UserInterestInfo,
    UserListInfo as UserListInfo,
    WebpageConditionInfo as WebpageConditionInfo,
    WebpageInfo as WebpageInfo,
    WebpageSampleInfo as WebpageSampleInfo,
    YouTubeChannelInfo as YouTubeChannelInfo,
    YouTubeVideoInfo as YouTubeVideoInfo,
)
from .types.criterion_category_availability import (
    CriterionCategoryAvailability as CriterionCategoryAvailability,
    CriterionCategoryChannelAvailability as CriterionCategoryChannelAvailability,
    CriterionCategoryLocaleAvailability as CriterionCategoryLocaleAvailability,
)
from .types.custom_parameter import CustomParameter as CustomParameter
from .types.customizer_value import CustomizerValue as CustomizerValue
from .types.dates import (
    DateRange as DateRange,
    YearMonth as YearMonth,
    YearMonthRange as YearMonthRange,
)
from .types.extensions import (
    CallFeedItem as CallFeedItem,
    CalloutFeedItem as CalloutFeedItem,
    SitelinkFeedItem as SitelinkFeedItem,
)
from .types.feed_common import Money as Money
from .types.final_app_url import FinalAppUrl as FinalAppUrl
from .types.frequency_cap import (
    FrequencyCapEntry as FrequencyCapEntry,
    FrequencyCapKey as FrequencyCapKey,
)
from .types.keyword_plan_common import (
    ConceptGroup as ConceptGroup,
    HistoricalMetricsOptions as HistoricalMetricsOptions,
    KeywordAnnotations as KeywordAnnotations,
    KeywordConcept as KeywordConcept,
    KeywordPlanAggregateMetricResults as KeywordPlanAggregateMetricResults,
    KeywordPlanAggregateMetrics as KeywordPlanAggregateMetrics,
    KeywordPlanDeviceSearches as KeywordPlanDeviceSearches,
    KeywordPlanHistoricalMetrics as KeywordPlanHistoricalMetrics,
    MonthlySearchVolume as MonthlySearchVolume,
)
from .types.lifecycle_goals import (
    LifecycleGoalValueSettings as LifecycleGoalValueSettings,
)
from .types.local_services import (
    LocalServicesDocumentReadOnly as LocalServicesDocumentReadOnly,
)
from .types.metric_goal import MetricGoal as MetricGoal
from .types.metrics import Metrics as Metrics, SearchVolumeRange as SearchVolumeRange
from .types.offline_user_data import (
    CustomerMatchUserListMetadata as CustomerMatchUserListMetadata,
    EventAttribute as EventAttribute,
    EventItemAttribute as EventItemAttribute,
    ItemAttribute as ItemAttribute,
    OfflineUserAddressInfo as OfflineUserAddressInfo,
    ShoppingLoyalty as ShoppingLoyalty,
    StoreAttribute as StoreAttribute,
    StoreSalesMetadata as StoreSalesMetadata,
    StoreSalesThirdPartyMetadata as StoreSalesThirdPartyMetadata,
    TransactionAttribute as TransactionAttribute,
    UserAttribute as UserAttribute,
    UserData as UserData,
    UserIdentifier as UserIdentifier,
)
from .types.policy import (
    PolicyTopicConstraint as PolicyTopicConstraint,
    PolicyTopicEntry as PolicyTopicEntry,
    PolicyTopicEvidence as PolicyTopicEvidence,
    PolicyValidationParameter as PolicyValidationParameter,
    PolicyViolationKey as PolicyViolationKey,
)
from .types.policy_summary import PolicySummary as PolicySummary
from .types.real_time_bidding_setting import (
    RealTimeBiddingSetting as RealTimeBiddingSetting,
)
from .types.segments import (
    AssetInteractionTarget as AssetInteractionTarget,
    BudgetCampaignAssociationStatus as BudgetCampaignAssociationStatus,
    Keyword as Keyword,
    Segments as Segments,
    SkAdNetworkSourceApp as SkAdNetworkSourceApp,
)
from .types.simulation import (
    BudgetSimulationPoint as BudgetSimulationPoint,
    BudgetSimulationPointList as BudgetSimulationPointList,
    CpcBidSimulationPoint as CpcBidSimulationPoint,
    CpcBidSimulationPointList as CpcBidSimulationPointList,
    CpvBidSimulationPoint as CpvBidSimulationPoint,
    CpvBidSimulationPointList as CpvBidSimulationPointList,
    PercentCpcBidSimulationPoint as PercentCpcBidSimulationPoint,
    PercentCpcBidSimulationPointList as PercentCpcBidSimulationPointList,
    TargetCpaSimulationPoint as TargetCpaSimulationPoint,
    TargetCpaSimulationPointList as TargetCpaSimulationPointList,
    TargetImpressionShareSimulationPoint as TargetImpressionShareSimulationPoint,
    TargetImpressionShareSimulationPointList as TargetImpressionShareSimulationPointList,
    TargetRoasSimulationPoint as TargetRoasSimulationPoint,
    TargetRoasSimulationPointList as TargetRoasSimulationPointList,
)
from .types.tag_snippet import TagSnippet as TagSnippet
from .types.targeting_setting import (
    TargetingSetting as TargetingSetting,
    TargetRestriction as TargetRestriction,
    TargetRestrictionOperation as TargetRestrictionOperation,
)
from .types.text_label import TextLabel as TextLabel
from .types.url_collection import UrlCollection as UrlCollection
from .types.user_lists import (
    BasicUserListInfo as BasicUserListInfo,
    CrmBasedUserListInfo as CrmBasedUserListInfo,
    FlexibleRuleOperandInfo as FlexibleRuleOperandInfo,
    FlexibleRuleUserListInfo as FlexibleRuleUserListInfo,
    LogicalUserListInfo as LogicalUserListInfo,
    LogicalUserListOperandInfo as LogicalUserListOperandInfo,
    LookalikeUserListInfo as LookalikeUserListInfo,
    RuleBasedUserListInfo as RuleBasedUserListInfo,
    SimilarUserListInfo as SimilarUserListInfo,
    UserListActionInfo as UserListActionInfo,
    UserListDateRuleItemInfo as UserListDateRuleItemInfo,
    UserListLogicalRuleInfo as UserListLogicalRuleInfo,
    UserListNumberRuleItemInfo as UserListNumberRuleItemInfo,
    UserListRuleInfo as UserListRuleInfo,
    UserListRuleItemGroupInfo as UserListRuleItemGroupInfo,
    UserListRuleItemInfo as UserListRuleItemInfo,
    UserListStringRuleItemInfo as UserListStringRuleItemInfo,
)
from .types.value import Value as Value

__all__ = [
    "ActivityCityInfo",
    "ActivityCountryInfo",
    "ActivityIdInfo",
    "ActivityRatingInfo",
    "ActivityStateInfo",
    "AdAppDeepLinkAsset",
    "AdAssetPolicySummary",
    "AdCallToActionAsset",
    "AdDemandGenCarouselCardAsset",
    "AdImageAsset",
    "AdMediaBundleAsset",
    "AdScheduleInfo",
    "AdTextAsset",
    "AdVideoAsset",
    "AdVideoAssetInfo",
    "AdVideoAssetInventoryPreferences",
    "AddressInfo",
    "AgeDimension",
    "AgeRangeInfo",
    "AgeSegment",
    "AppAdInfo",
    "AppDeepLinkAsset",
    "AppEngagementAdInfo",
    "AppPaymentModelInfo",
    "AppPreRegistrationAdInfo",
    "AssetDisapproved",
    "AssetInteractionTarget",
    "AssetLinkPrimaryStatusDetails",
    "AssetUsage",
    "AudienceDimension",
    "AudienceExclusionDimension",
    "AudienceInfo",
    "AudienceInsightsAttribute",
    "AudienceInsightsAttributeMetadata",
    "AudienceInsightsCategory",
    "AudienceInsightsDynamicLineup",
    "AudienceInsightsEntity",
    "AudienceInsightsTopic",
    "AudienceSegment",
    "AudienceSegmentDimension",
    "BasicUserListInfo",
    "BookOnGoogleAsset",
    "BrandInfo",
    "BrandListInfo",
    "BudgetCampaignAssociationStatus",
    "BudgetSimulationPoint",
    "BudgetSimulationPointList",
    "BusinessMessageAsset",
    "BusinessMessageCallToActionInfo",
    "BusinessProfileBusinessNameFilter",
    "BusinessProfileLocation",
    "BusinessProfileLocationGroup",
    "BusinessProfileLocationSet",
    "CallAdInfo",
    "CallAsset",
    "CallFeedItem",
    "CallToActionAsset",
    "CalloutAsset",
    "CalloutFeedItem",
    "CarrierInfo",
    "ChainFilter",
    "ChainLocationGroup",
    "ChainSet",
    "ClickLocation",
    "CombinedAudienceInfo",
    "Commission",
    "ConceptGroup",
    "Consent",
    "ContentLabelInfo",
    "CpcBidSimulationPoint",
    "CpcBidSimulationPointList",
    "CpvBidSimulationPoint",
    "CpvBidSimulationPointList",
    "CriterionCategoryAvailability",
    "CriterionCategoryChannelAvailability",
    "CriterionCategoryLocaleAvailability",
    "CrmBasedUserListInfo",
    "CustomAffinityInfo",
    "CustomAudienceInfo",
    "CustomAudienceSegment",
    "CustomIntentInfo",
    "CustomParameter",
    "CustomerMatchUserListMetadata",
    "CustomizerValue",
    "DateRange",
    "DemandGenCarouselAdInfo",
    "DemandGenCarouselCardAsset",
    "DemandGenMultiAssetAdInfo",
    "DemandGenProductAdInfo",
    "DemandGenVideoResponsiveAdInfo",
    "DetailedDemographicSegment",
    "DeviceInfo",
    "DisplayUploadAdInfo",
    "DynamicBusinessProfileLocationGroupFilter",
    "DynamicCustomAsset",
    "DynamicEducationAsset",
    "DynamicFlightsAsset",
    "DynamicHotelsAndRentalsAsset",
    "DynamicJobsAsset",
    "DynamicLineupAttributeMetadata",
    "DynamicLocalAsset",
    "DynamicRealEstateAsset",
    "DynamicTravelAsset",
    "EnhancedCpc",
    "EventAttribute",
    "EventItemAttribute",
    "ExclusionSegment",
    "ExpandedDynamicSearchAdInfo",
    "ExpandedTextAdInfo",
    "FinalAppUrl",
    "FixedCpm",
    "FixedCpmTargetFrequencyGoalInfo",
    "FlexibleRuleOperandInfo",
    "FlexibleRuleUserListInfo",
    "FrequencyCapEntry",
    "FrequencyCapKey",
    "GenderDimension",
    "GenderInfo",
    "GeoPointInfo",
    "HistoricalMetricsOptions",
    "HotelAdInfo",
    "HotelAdvanceBookingWindowInfo",
    "HotelCalloutAsset",
    "HotelCheckInDateRangeInfo",
    "HotelCheckInDayInfo",
    "HotelCityInfo",
    "HotelClassInfo",
    "HotelCountryRegionInfo",
    "HotelDateSelectionTypeInfo",
    "HotelIdInfo",
    "HotelLengthOfStayInfo",
    "HotelPropertyAsset",
    "HotelStateInfo",
    "HouseholdIncomeDimension",
    "ImageAdInfo",
    "ImageAsset",
    "ImageDimension",
    "InFeedVideoAdInfo",
    "IncomeRangeInfo",
    "InteractionTypeInfo",
    "IpBlockInfo",
    "ItemAttribute",
    "Keyword",
    "KeywordAnnotations",
    "KeywordConcept",
    "KeywordInfo",
    "KeywordPlanAggregateMetricResults",
    "KeywordPlanAggregateMetrics",
    "KeywordPlanDeviceSearches",
    "KeywordPlanHistoricalMetrics",
    "KeywordThemeInfo",
    "KnowledgeGraphAttributeMetadata",
    "LanguageInfo",
    "LeadFormAsset",
    "LeadFormCustomQuestionField",
    "LeadFormDeliveryMethod",
    "LeadFormField",
    "LeadFormSingleChoiceAnswers",
    "LegacyAppInstallAdInfo",
    "LegacyResponsiveDisplayAdInfo",
    "LifeEventSegment",
    "LifecycleGoalValueSettings",
    "ListingDimensionInfo",
    "ListingDimensionPath",
    "ListingGroupInfo",
    "ListingScopeInfo",
    "LocalAdInfo",
    "LocalServiceIdInfo",
    "LocalServicesDocumentReadOnly",
    "LocationAsset",
    "LocationAttributeMetadata",
    "LocationGroupInfo",
    "LocationInfo",
    "LocationSet",
    "LogicalUserListInfo",
    "LogicalUserListOperandInfo",
    "LookalikeUserListInfo",
    "ManualCpa",
    "ManualCpc",
    "ManualCpm",
    "ManualCpv",
    "MapsLocationInfo",
    "MapsLocationSet",
    "MaximizeConversionValue",
    "MaximizeConversions",
    "MediaBundleAsset",
    "MetricGoal",
    "Metrics",
    "MobileAppAsset",
    "MobileAppCategoryInfo",
    "MobileApplicationInfo",
    "MobileDeviceInfo",
    "Money",
    "MonthlySearchVolume",
    "NegativeKeywordListInfo",
    "OfflineUserAddressInfo",
    "OperatingSystemVersionInfo",
    "PageFeedAsset",
    "ParentalStatusDimension",
    "ParentalStatusInfo",
    "PercentCpc",
    "PercentCpcBidSimulationPoint",
    "PercentCpcBidSimulationPointList",
    "PlacementInfo",
    "PolicySummary",
    "PolicyTopicConstraint",
    "PolicyTopicEntry",
    "PolicyTopicEvidence",
    "PolicyValidationParameter",
    "PolicyViolationKey",
    "PriceAsset",
    "PriceOffering",
    "ProductBrandInfo",
    "ProductCategoryInfo",
    "ProductChannelExclusivityInfo",
    "ProductChannelInfo",
    "ProductConditionInfo",
    "ProductCustomAttributeInfo",
    "ProductGroupingInfo",
    "ProductItemIdInfo",
    "ProductLabelsInfo",
    "ProductLegacyConditionInfo",
    "ProductTypeFullInfo",
    "ProductTypeInfo",
    "PromotionAsset",
    "ProximityInfo",
    "RealTimeBiddingSetting",
    "ResponsiveDisplayAdControlSpec",
    "ResponsiveDisplayAdInfo",
    "ResponsiveSearchAdInfo",
    "RuleBasedUserListInfo",
    "SearchThemeInfo",
    "SearchVolumeRange",
    "Segments",
    "ShoppingComparisonListingAdInfo",
    "ShoppingLoyalty",
    "ShoppingProductAdInfo",
    "ShoppingSmartAdInfo",
    "SimilarUserListInfo",
    "SitelinkAsset",
    "SitelinkFeedItem",
    "SkAdNetworkSourceApp",
    "SmartCampaignAdInfo",
    "StoreAttribute",
    "StoreSalesMetadata",
    "StoreSalesThirdPartyMetadata",
    "StructuredSnippetAsset",
    "TagSnippet",
    "TargetCpa",
    "TargetCpaSimulationPoint",
    "TargetCpaSimulationPointList",
    "TargetCpm",
    "TargetCpmTargetFrequencyGoal",
    "TargetCpv",
    "TargetImpressionShare",
    "TargetImpressionShareSimulationPoint",
    "TargetImpressionShareSimulationPointList",
    "TargetRestriction",
    "TargetRestrictionOperation",
    "TargetRoas",
    "TargetRoasSimulationPoint",
    "TargetRoasSimulationPointList",
    "TargetSpend",
    "TargetingSetting",
    "TextAdInfo",
    "TextAsset",
    "TextLabel",
    "TopicInfo",
    "TransactionAttribute",
    "TravelAdInfo",
    "UnknownListingDimensionInfo",
    "UrlCollection",
    "UserAttribute",
    "UserData",
    "UserIdentifier",
    "UserInterestAttributeMetadata",
    "UserInterestInfo",
    "UserInterestSegment",
    "UserListActionInfo",
    "UserListDateRuleItemInfo",
    "UserListInfo",
    "UserListLogicalRuleInfo",
    "UserListNumberRuleItemInfo",
    "UserListRuleInfo",
    "UserListRuleItemGroupInfo",
    "UserListRuleItemInfo",
    "UserListSegment",
    "UserListStringRuleItemInfo",
    "Value",
    "VideoAdInfo",
    "VideoBumperInStreamAdInfo",
    "VideoNonSkippableInStreamAdInfo",
    "VideoOutstreamAdInfo",
    "VideoResponsiveAdInfo",
    "VideoTrueViewInStreamAdInfo",
    "WebhookDelivery",
    "WebpageConditionInfo",
    "WebpageInfo",
    "WebpageSampleInfo",
    "WhatsappBusinessMessageInfo",
    "YearMonth",
    "YearMonthRange",
    "YouTubeChannelAttributeMetadata",
    "YouTubeChannelInfo",
    "YouTubeVideoAttributeMetadata",
    "YouTubeVideoInfo",
    "YoutubeVideoAsset",
]
