# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class BudgetDeliveryMethodEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    BudgetDeliveryMethodValue = typing___NewType(
        "BudgetDeliveryMethodValue", builtin___int
    )
    type___BudgetDeliveryMethodValue = BudgetDeliveryMethodValue
    BudgetDeliveryMethod: _BudgetDeliveryMethod
    class _BudgetDeliveryMethod(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(
            BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 0
        )
        UNKNOWN = typing___cast(BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 1)
        STANDARD = typing___cast(BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 2)
        ACCELERATED = typing___cast(
            BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 3
        )
    UNSPECIFIED = typing___cast(BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 0)
    UNKNOWN = typing___cast(BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 1)
    STANDARD = typing___cast(BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 2)
    ACCELERATED = typing___cast(BudgetDeliveryMethodEnum.BudgetDeliveryMethodValue, 3)
    type___BudgetDeliveryMethod = BudgetDeliveryMethod
    def __init__(self,) -> None: ...

type___BudgetDeliveryMethodEnum = BudgetDeliveryMethodEnum
