"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class CustomInterestMemberTypeEnum(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _CustomInterestMemberType(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            CustomInterestMemberType.V
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNSPECIFIED = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(0)
        UNKNOWN = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(1)
        KEYWORD = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(2)
        URL = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(3)
    class CustomInterestMemberType(metaclass=_CustomInterestMemberType):
        V = typing.NewType("V", builtins.int)
    UNSPECIFIED = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(0)
    UNKNOWN = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(1)
    KEYWORD = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(2)
    URL = CustomInterestMemberTypeEnum.CustomInterestMemberType.V(3)
    def __init__(
        self,
    ) -> None: ...

global___CustomInterestMemberTypeEnum = CustomInterestMemberTypeEnum
