# @generated by mypy-protobuf.  Do not edit manually!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class UserListClosingReasonEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    UserListClosingReasonValue = typing___NewType(
        "UserListClosingReasonValue", builtin___int
    )
    type___UserListClosingReasonValue = UserListClosingReasonValue
    UserListClosingReason: _UserListClosingReason
    class _UserListClosingReason(
        google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
            UserListClosingReasonEnum.UserListClosingReasonValue
        ]
    ):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(
            UserListClosingReasonEnum.UserListClosingReasonValue, 0
        )
        UNKNOWN = typing___cast(UserListClosingReasonEnum.UserListClosingReasonValue, 1)
        UNUSED = typing___cast(UserListClosingReasonEnum.UserListClosingReasonValue, 2)
    UNSPECIFIED = typing___cast(UserListClosingReasonEnum.UserListClosingReasonValue, 0)
    UNKNOWN = typing___cast(UserListClosingReasonEnum.UserListClosingReasonValue, 1)
    UNUSED = typing___cast(UserListClosingReasonEnum.UserListClosingReasonValue, 2)
    type___UserListClosingReason = UserListClosingReason
    def __init__(self,) -> None: ...

type___UserListClosingReasonEnum = UserListClosingReasonEnum
