name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: poetry install
      
      - name: Run Black
        run: poetry run black --check google-stubs
      
      - name: Run isort
        run: poetry run isort --check-only google-stubs
      
      - name: Run Mypy
        run: |
          mv google-stubs google
          poetry run mypy google
