# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import Message as google___protobuf___message___Message

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    Union as typing___Union,
    cast as typing___cast,
)

builtin___bytes = bytes
builtin___int = int
builtin___str = str
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode

class AdCustomizerErrorEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class AdCustomizerError(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(
            cls, name: builtin___str
        ) -> "AdCustomizerErrorEnum.AdCustomizerError": ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List["AdCustomizerErrorEnum.AdCustomizerError"]: ...
        @classmethod
        def items(
            cls,
        ) -> typing___List[
            typing___Tuple[builtin___str, "AdCustomizerErrorEnum.AdCustomizerError"]
        ]: ...
        UNSPECIFIED = typing___cast("AdCustomizerErrorEnum.AdCustomizerError", 0)
        UNKNOWN = typing___cast("AdCustomizerErrorEnum.AdCustomizerError", 1)
        COUNTDOWN_INVALID_DATE_FORMAT = typing___cast(
            "AdCustomizerErrorEnum.AdCustomizerError", 2
        )
        COUNTDOWN_DATE_IN_PAST = typing___cast(
            "AdCustomizerErrorEnum.AdCustomizerError", 3
        )
        COUNTDOWN_INVALID_LOCALE = typing___cast(
            "AdCustomizerErrorEnum.AdCustomizerError", 4
        )
        COUNTDOWN_INVALID_START_DAYS_BEFORE = typing___cast(
            "AdCustomizerErrorEnum.AdCustomizerError", 5
        )
        UNKNOWN_USER_LIST = typing___cast("AdCustomizerErrorEnum.AdCustomizerError", 6)
    UNSPECIFIED = typing___cast("AdCustomizerErrorEnum.AdCustomizerError", 0)
    UNKNOWN = typing___cast("AdCustomizerErrorEnum.AdCustomizerError", 1)
    COUNTDOWN_INVALID_DATE_FORMAT = typing___cast(
        "AdCustomizerErrorEnum.AdCustomizerError", 2
    )
    COUNTDOWN_DATE_IN_PAST = typing___cast("AdCustomizerErrorEnum.AdCustomizerError", 3)
    COUNTDOWN_INVALID_LOCALE = typing___cast(
        "AdCustomizerErrorEnum.AdCustomizerError", 4
    )
    COUNTDOWN_INVALID_START_DAYS_BEFORE = typing___cast(
        "AdCustomizerErrorEnum.AdCustomizerError", 5
    )
    UNKNOWN_USER_LIST = typing___cast("AdCustomizerErrorEnum.AdCustomizerError", 6)
    global___AdCustomizerError = AdCustomizerError
    def __init__(self,) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> AdCustomizerErrorEnum: ...
    else:
        @classmethod
        def FromString(
            cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]
        ) -> AdCustomizerErrorEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

global___AdCustomizerErrorEnum = AdCustomizerErrorEnum
