# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class BiddingErrorEnum(google___protobuf___message___Message):
    class BiddingError(object):
        ClosedKeyType = typing___Union[typing_extensions___Literal['UNSPECIFIED'],typing_extensions___Literal['UNKNOWN'],typing_extensions___Literal['BIDDING_STRATEGY_TRANSITION_NOT_ALLOWED'],typing_extensions___Literal['CANNOT_ATTACH_BIDDING_STRATEGY_TO_CAMPAIGN'],typing_extensions___Literal['INVALID_ANONYMOUS_BIDDING_STRATEGY_TYPE'],typing_extensions___Literal['INVALID_BIDDING_STRATEGY_TYPE'],typing_extensions___Literal['INVALID_BID'],typing_extensions___Literal['BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE'],typing_extensions___Literal['CONVERSION_TRACKING_NOT_ENABLED'],typing_extensions___Literal['NOT_ENOUGH_CONVERSIONS'],typing_extensions___Literal['CANNOT_CREATE_CAMPAIGN_WITH_BIDDING_STRATEGY'],typing_extensions___Literal['CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CAMPAIGN_LEVEL_POP_BIDDING_STRATEGY'],typing_extensions___Literal['BIDDING_STRATEGY_NOT_SUPPORTED_WITH_AD_SCHEDULE'],typing_extensions___Literal['PAY_PER_CONVERSION_NOT_AVAILABLE_FOR_CUSTOMER'],typing_extensions___Literal['PAY_PER_CONVERSION_NOT_ALLOWED_WITH_TARGET_CPA'],typing_extensions___Literal['BIDDING_STRATEGY_NOT_ALLOWED_FOR_SEARCH_ONLY_CAMPAIGNS'],typing_extensions___Literal['BIDDING_STRATEGY_NOT_SUPPORTED_IN_DRAFTS_OR_EXPERIMENTS'],typing_extensions___Literal['BIDDING_STRATEGY_TYPE_DOES_NOT_SUPPORT_PRODUCT_TYPE_ADGROUP_CRITERION'],typing_extensions___Literal['BID_TOO_SMALL'],typing_extensions___Literal['BID_TOO_BIG'],typing_extensions___Literal['BID_TOO_MANY_FRACTIONAL_DIGITS'],typing_extensions___Literal['INVALID_DOMAIN_NAME'],typing_extensions___Literal['NOT_COMPATIBLE_WITH_PAYMENT_MODE'],typing_extensions___Literal['NOT_COMPATIBLE_WITH_BUDGET_TYPE'],typing_extensions___Literal['NOT_COMPATIBLE_WITH_BIDDING_STRATEGY_TYPE']]
        ClosedValueType = typing___Union[typing_extensions___Literal[0],typing_extensions___Literal[1],typing_extensions___Literal[2],typing_extensions___Literal[7],typing_extensions___Literal[10],typing_extensions___Literal[14],typing_extensions___Literal[17],typing_extensions___Literal[18],typing_extensions___Literal[19],typing_extensions___Literal[20],typing_extensions___Literal[21],typing_extensions___Literal[23],typing_extensions___Literal[24],typing_extensions___Literal[25],typing_extensions___Literal[26],typing_extensions___Literal[27],typing_extensions___Literal[28],typing_extensions___Literal[29],typing_extensions___Literal[30],typing_extensions___Literal[31],typing_extensions___Literal[32],typing_extensions___Literal[33],typing_extensions___Literal[34],typing_extensions___Literal[35],typing_extensions___Literal[36]]
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: ClosedValueType) -> str: ...
        @classmethod
        def Value(cls, name: ClosedKeyType) -> ClosedValueType: ...
        @classmethod
        def keys(cls) -> typing___List[ClosedKeyType]: ...
        @classmethod
        def values(cls) -> typing___List[ClosedValueType]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[ClosedKeyType, ClosedValueType]]: ...
        UNSPECIFIED: typing_extensions___Literal[0]
        UNKNOWN: typing_extensions___Literal[1]
        BIDDING_STRATEGY_TRANSITION_NOT_ALLOWED: typing_extensions___Literal[2]
        CANNOT_ATTACH_BIDDING_STRATEGY_TO_CAMPAIGN: typing_extensions___Literal[7]
        INVALID_ANONYMOUS_BIDDING_STRATEGY_TYPE: typing_extensions___Literal[10]
        INVALID_BIDDING_STRATEGY_TYPE: typing_extensions___Literal[14]
        INVALID_BID: typing_extensions___Literal[17]
        BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE: typing_extensions___Literal[18]
        CONVERSION_TRACKING_NOT_ENABLED: typing_extensions___Literal[19]
        NOT_ENOUGH_CONVERSIONS: typing_extensions___Literal[20]
        CANNOT_CREATE_CAMPAIGN_WITH_BIDDING_STRATEGY: typing_extensions___Literal[21]
        CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CAMPAIGN_LEVEL_POP_BIDDING_STRATEGY: typing_extensions___Literal[23]
        BIDDING_STRATEGY_NOT_SUPPORTED_WITH_AD_SCHEDULE: typing_extensions___Literal[24]
        PAY_PER_CONVERSION_NOT_AVAILABLE_FOR_CUSTOMER: typing_extensions___Literal[25]
        PAY_PER_CONVERSION_NOT_ALLOWED_WITH_TARGET_CPA: typing_extensions___Literal[26]
        BIDDING_STRATEGY_NOT_ALLOWED_FOR_SEARCH_ONLY_CAMPAIGNS: typing_extensions___Literal[27]
        BIDDING_STRATEGY_NOT_SUPPORTED_IN_DRAFTS_OR_EXPERIMENTS: typing_extensions___Literal[28]
        BIDDING_STRATEGY_TYPE_DOES_NOT_SUPPORT_PRODUCT_TYPE_ADGROUP_CRITERION: typing_extensions___Literal[29]
        BID_TOO_SMALL: typing_extensions___Literal[30]
        BID_TOO_BIG: typing_extensions___Literal[31]
        BID_TOO_MANY_FRACTIONAL_DIGITS: typing_extensions___Literal[32]
        INVALID_DOMAIN_NAME: typing_extensions___Literal[33]
        NOT_COMPATIBLE_WITH_PAYMENT_MODE: typing_extensions___Literal[34]
        NOT_COMPATIBLE_WITH_BUDGET_TYPE: typing_extensions___Literal[35]
        NOT_COMPATIBLE_WITH_BIDDING_STRATEGY_TYPE: typing_extensions___Literal[36]
    UNSPECIFIED: typing_extensions___Literal[0]
    UNKNOWN: typing_extensions___Literal[1]
    BIDDING_STRATEGY_TRANSITION_NOT_ALLOWED: typing_extensions___Literal[2]
    CANNOT_ATTACH_BIDDING_STRATEGY_TO_CAMPAIGN: typing_extensions___Literal[7]
    INVALID_ANONYMOUS_BIDDING_STRATEGY_TYPE: typing_extensions___Literal[10]
    INVALID_BIDDING_STRATEGY_TYPE: typing_extensions___Literal[14]
    INVALID_BID: typing_extensions___Literal[17]
    BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE: typing_extensions___Literal[18]
    CONVERSION_TRACKING_NOT_ENABLED: typing_extensions___Literal[19]
    NOT_ENOUGH_CONVERSIONS: typing_extensions___Literal[20]
    CANNOT_CREATE_CAMPAIGN_WITH_BIDDING_STRATEGY: typing_extensions___Literal[21]
    CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CAMPAIGN_LEVEL_POP_BIDDING_STRATEGY: typing_extensions___Literal[23]
    BIDDING_STRATEGY_NOT_SUPPORTED_WITH_AD_SCHEDULE: typing_extensions___Literal[24]
    PAY_PER_CONVERSION_NOT_AVAILABLE_FOR_CUSTOMER: typing_extensions___Literal[25]
    PAY_PER_CONVERSION_NOT_ALLOWED_WITH_TARGET_CPA: typing_extensions___Literal[26]
    BIDDING_STRATEGY_NOT_ALLOWED_FOR_SEARCH_ONLY_CAMPAIGNS: typing_extensions___Literal[27]
    BIDDING_STRATEGY_NOT_SUPPORTED_IN_DRAFTS_OR_EXPERIMENTS: typing_extensions___Literal[28]
    BIDDING_STRATEGY_TYPE_DOES_NOT_SUPPORT_PRODUCT_TYPE_ADGROUP_CRITERION: typing_extensions___Literal[29]
    BID_TOO_SMALL: typing_extensions___Literal[30]
    BID_TOO_BIG: typing_extensions___Literal[31]
    BID_TOO_MANY_FRACTIONAL_DIGITS: typing_extensions___Literal[32]
    INVALID_DOMAIN_NAME: typing_extensions___Literal[33]
    NOT_COMPATIBLE_WITH_PAYMENT_MODE: typing_extensions___Literal[34]
    NOT_COMPATIBLE_WITH_BUDGET_TYPE: typing_extensions___Literal[35]
    NOT_COMPATIBLE_WITH_BIDDING_STRATEGY_TYPE: typing_extensions___Literal[36]


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> BiddingErrorEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
