# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class FeedMappingErrorEnum(google___protobuf___message___Message):
    class FeedMappingError(object):
        ClosedKeyType = typing___Union[typing_extensions___Literal['UNSPECIFIED'],typing_extensions___Literal['UNKNOWN'],typing_extensions___Literal['INVALID_PLACEHOLDER_FIELD'],typing_extensions___Literal['INVALID_CRITERION_FIELD'],typing_extensions___Literal['INVALID_PLACEHOLDER_TYPE'],typing_extensions___Literal['INVALID_CRITERION_TYPE'],typing_extensions___Literal['NO_ATTRIBUTE_FIELD_MAPPINGS'],typing_extensions___Literal['FEED_ATTRIBUTE_TYPE_MISMATCH'],typing_extensions___Literal['CANNOT_OPERATE_ON_MAPPINGS_FOR_SYSTEM_GENERATED_FEED'],typing_extensions___Literal['MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_TYPE'],typing_extensions___Literal['MULTIPLE_MAPPINGS_FOR_CRITERION_TYPE'],typing_extensions___Literal['MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_FIELD'],typing_extensions___Literal['MULTIPLE_MAPPINGS_FOR_CRITERION_FIELD'],typing_extensions___Literal['UNEXPECTED_ATTRIBUTE_FIELD_MAPPINGS'],typing_extensions___Literal['LOCATION_PLACEHOLDER_ONLY_FOR_PLACES_FEEDS'],typing_extensions___Literal['CANNOT_MODIFY_MAPPINGS_FOR_TYPED_FEED'],typing_extensions___Literal['INVALID_PLACEHOLDER_TYPE_FOR_NON_SYSTEM_GENERATED_FEED'],typing_extensions___Literal['INVALID_PLACEHOLDER_TYPE_FOR_SYSTEM_GENERATED_FEED_TYPE']]
        ClosedValueType = typing___Union[typing_extensions___Literal[0],typing_extensions___Literal[1],typing_extensions___Literal[2],typing_extensions___Literal[3],typing_extensions___Literal[4],typing_extensions___Literal[5],typing_extensions___Literal[7],typing_extensions___Literal[8],typing_extensions___Literal[9],typing_extensions___Literal[10],typing_extensions___Literal[11],typing_extensions___Literal[12],typing_extensions___Literal[13],typing_extensions___Literal[14],typing_extensions___Literal[15],typing_extensions___Literal[16],typing_extensions___Literal[17],typing_extensions___Literal[18]]
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: ClosedValueType) -> str: ...
        @classmethod
        def Value(cls, name: ClosedKeyType) -> ClosedValueType: ...
        @classmethod
        def keys(cls) -> typing___List[ClosedKeyType]: ...
        @classmethod
        def values(cls) -> typing___List[ClosedValueType]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[ClosedKeyType, ClosedValueType]]: ...
        UNSPECIFIED: typing_extensions___Literal[0]
        UNKNOWN: typing_extensions___Literal[1]
        INVALID_PLACEHOLDER_FIELD: typing_extensions___Literal[2]
        INVALID_CRITERION_FIELD: typing_extensions___Literal[3]
        INVALID_PLACEHOLDER_TYPE: typing_extensions___Literal[4]
        INVALID_CRITERION_TYPE: typing_extensions___Literal[5]
        NO_ATTRIBUTE_FIELD_MAPPINGS: typing_extensions___Literal[7]
        FEED_ATTRIBUTE_TYPE_MISMATCH: typing_extensions___Literal[8]
        CANNOT_OPERATE_ON_MAPPINGS_FOR_SYSTEM_GENERATED_FEED: typing_extensions___Literal[9]
        MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_TYPE: typing_extensions___Literal[10]
        MULTIPLE_MAPPINGS_FOR_CRITERION_TYPE: typing_extensions___Literal[11]
        MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_FIELD: typing_extensions___Literal[12]
        MULTIPLE_MAPPINGS_FOR_CRITERION_FIELD: typing_extensions___Literal[13]
        UNEXPECTED_ATTRIBUTE_FIELD_MAPPINGS: typing_extensions___Literal[14]
        LOCATION_PLACEHOLDER_ONLY_FOR_PLACES_FEEDS: typing_extensions___Literal[15]
        CANNOT_MODIFY_MAPPINGS_FOR_TYPED_FEED: typing_extensions___Literal[16]
        INVALID_PLACEHOLDER_TYPE_FOR_NON_SYSTEM_GENERATED_FEED: typing_extensions___Literal[17]
        INVALID_PLACEHOLDER_TYPE_FOR_SYSTEM_GENERATED_FEED_TYPE: typing_extensions___Literal[18]
    UNSPECIFIED: typing_extensions___Literal[0]
    UNKNOWN: typing_extensions___Literal[1]
    INVALID_PLACEHOLDER_FIELD: typing_extensions___Literal[2]
    INVALID_CRITERION_FIELD: typing_extensions___Literal[3]
    INVALID_PLACEHOLDER_TYPE: typing_extensions___Literal[4]
    INVALID_CRITERION_TYPE: typing_extensions___Literal[5]
    NO_ATTRIBUTE_FIELD_MAPPINGS: typing_extensions___Literal[7]
    FEED_ATTRIBUTE_TYPE_MISMATCH: typing_extensions___Literal[8]
    CANNOT_OPERATE_ON_MAPPINGS_FOR_SYSTEM_GENERATED_FEED: typing_extensions___Literal[9]
    MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_TYPE: typing_extensions___Literal[10]
    MULTIPLE_MAPPINGS_FOR_CRITERION_TYPE: typing_extensions___Literal[11]
    MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_FIELD: typing_extensions___Literal[12]
    MULTIPLE_MAPPINGS_FOR_CRITERION_FIELD: typing_extensions___Literal[13]
    UNEXPECTED_ATTRIBUTE_FIELD_MAPPINGS: typing_extensions___Literal[14]
    LOCATION_PLACEHOLDER_ONLY_FOR_PLACES_FEEDS: typing_extensions___Literal[15]
    CANNOT_MODIFY_MAPPINGS_FOR_TYPED_FEED: typing_extensions___Literal[16]
    INVALID_PLACEHOLDER_TYPE_FOR_NON_SYSTEM_GENERATED_FEED: typing_extensions___Literal[17]
    INVALID_PLACEHOLDER_TYPE_FOR_SYSTEM_GENERATED_FEED_TYPE: typing_extensions___Literal[18]


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> FeedMappingErrorEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
