# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class SizeLimitErrorEnum(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class SizeLimitError(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> SizeLimitErrorEnum.SizeLimitError: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[SizeLimitErrorEnum.SizeLimitError]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, SizeLimitErrorEnum.SizeLimitError]]: ...
        UNSPECIFIED = typing___cast(SizeLimitErrorEnum.SizeLimitError, 0)
        UNKNOWN = typing___cast(SizeLimitErrorEnum.SizeLimitError, 1)
        REQUEST_SIZE_LIMIT_EXCEEDED = typing___cast(SizeLimitErrorEnum.SizeLimitError, 2)
        RESPONSE_SIZE_LIMIT_EXCEEDED = typing___cast(SizeLimitErrorEnum.SizeLimitError, 3)
    UNSPECIFIED = typing___cast(SizeLimitErrorEnum.SizeLimitError, 0)
    UNKNOWN = typing___cast(SizeLimitErrorEnum.SizeLimitError, 1)
    REQUEST_SIZE_LIMIT_EXCEEDED = typing___cast(SizeLimitErrorEnum.SizeLimitError, 2)
    RESPONSE_SIZE_LIMIT_EXCEEDED = typing___cast(SizeLimitErrorEnum.SizeLimitError, 3)


    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SizeLimitErrorEnum: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
